<?php
// $Id: superadmin.module,v 1.15.2.22 2009/05/03 23:00:18  Exp $
/**
 * @file
*/
function superadmin_menu() {

  $items['superadmin/login'] = array(
   'title' => 'Superadmin',
   'page callback' => 'drupal_get_form',
   'page arguments' => array('superadmin_login_form'),
   'access arguments' => array('superadmin register'),
   'access callback' => 'superadmin_access',
   'type' => MENU_CALLBACK,
  );
  $items['superadmin/stafflist'] = array(
   'title' => 'Staff List',
   'page callback' => 'staff_list',
   'access callback' => 'superadmin_access',
   'type' => MENU_CALLBACK
  );
  $items['dean_department'] = array(
   'page callback' => 'dean_department',
   'access arguments' => array('superadmin register'),
   'access callback' => 'superadmin_access',
   'type' => MENU_CALLBACK,
  );
  $items['superadmin/assignrole'] = array(
   'title' => 'Assign role',
   'page callback' => 'drupal_get_form',
   'page arguments' => array('assign_role_form'),
   'access arguments' => array('superadmin register'),
   'access callback' => 'superadmin_access',
   'type' => MENU_CALLBACK,
  );
  return $items;
}

function assign_drupal_role($user_id, $role) {
  if ($user_id == "") {
   return ;
  }
  $user = user_load($user_id);
  $query = "select r.* from {veritas_staff_role} sr inner join {role} r on r.name = sr.name where sr.id = ' $role '";
  $result = db_query($query);
  //echo  "select * from student where jambno = '".$form['#post']['jamb_no']."' and Admitted = 'Yes'" ; die ;
  $data = db_fetch_object($result);
  if (!isset($data->rid)) {
   return ;
  }
  $roles = array($data->rid => $data->rid);
  user_save($user , array('status' => 1, 'roles' => $roles));
}

function assign_role_form_submit($form , &$state) {
  $values = $form['#post'];
  if ($state['storage']['step'] == 1) {
   assign_drupal_role($values['user_id'] , $values['staff_role']);
   $query = 'Update {veritas_staff} set usrname = "'. $values['username'] .'" , password = "'. $values['password'] .'" ,  role_id ="'. $values['staff_role'] .'" where staff_id='. $values['staff_id'];
   db_query($query);
  }
  if ($state['storage']['step'] == 2) {
   $query = 'Update {veritas_staff} set parent_id ="'. $values['staff_parent'] .'" where staff_id='. $values['staff_id'];
   db_query($query);
   $query = 'delete from  {veritas_staff_department}  where staff_id='. arg(2);
   db_query($query);
   $query = "insert {veritas_staff_department} set staff_id=". arg(2) ." , department_id='". $state['values']['staff_department'] ."' ";
   db_query($query);
   drupal_set_message('Role Assigned');
   drupal_goto("superadmin/stafflist");
  }
  if ($state['storage']['step'] == 3) {
   $query = 'delete from  {veritas_staff_college}  where staff_id='. arg(2);
   db_query($query);
   $query = "insert {veritas_staff_college} set staff_id=". arg(2) ." , assigned_college='". $state['values']['staff_college'] ."' ";
   db_query($query);
   drupal_set_message('Role Assigned');
   drupal_goto("superadmin/stafflist");
  }
  if ($state['storage']['step'] == 4) {
   $query = 'Update {veritas_staff} set parent_id ="'. $values['staff_parent'] .'" where staff_id='. $values['staff_id'];
   db_query($query);
   $query = 'delete from  {veritas_staff_college}  where staff_id='. arg(2);
   db_query($query);
   $query = "insert {veritas_staff_college} set staff_id=". arg(2) ." , assigned_college='". $state['values']['staff_college'] ."' ";
   db_query($query);
   drupal_set_message('Role Assigned');
   drupal_goto("superadmin/stafflist");
  }
  if ($state['storage']['step'] == 5) {
   $query = 'Update {veritas_staff} set parent_id ="'. $values['staff_parent'] .'" where staff_id='. $values['staff_id'];
   db_query($query);
   drupal_set_message('Role Assigned');
   drupal_goto("superadmin/stafflist");
  }
  if ($state['storage']['step'] == 6) {
   $query = 'Update {veritas_staff} set parent_id ="'. $values['staff_parent'] .'" where staff_id='. $values['staff_id'];
   db_query($query);
   drupal_set_message('Role Assigned');
   drupal_goto("superadmin/stafflist");
  }
  if ($state['storage']['step'] == 7) {
   $query = 'Update {veritas_staff} set parent_id ="'. $values['staff_parent'] .'" where staff_id='. $values['staff_id'];
   db_query($query);
   drupal_set_message('Role Assigned');
   drupal_goto("superadmin/stafflist");
  }
  if ($state['clicked_button']['#id'] == 'edit-previous') {
   $state['storage']['step']--;
   $state['#rebuild'] = TRUE;
   return;
  }
  elseif ($state['clicked_button']['#id'] == 'edit-next') {
   $state['storage']['values'][$state['storage']['step']] = $state['values'];
   $state['#rebuild'] = TRUE;
   if ($state['storage']['step'] == 1) {
    switch ($values['staff_role']) {
      case 7:
        $state['storage']['step']++;
        break;
      case 6:
        $state['storage']['step'] = 3;
      break;
      case 5:
      case 4:
         $state['storage']['step'] = 4;
      break;
      case 8:
         $state['storage']['step'] = 5;
      break;
      case 10:
        $state['storage']['step'] = 7;
      break ;
      case 1:
      case 2:
      case 3:
      case 11:
      case 13:
        drupal_set_message('Role Assigned');
        drupal_goto("superadmin/stafflist");
      break;
      case 14 :
        $state['storage']['step'] = 6;
      break ;
     }
   }
  return;
  }
}
function assign_role_form(&$obj) {
  // if(!isset($_SESSION['student']['data']->student_id)){
  //  drupal_goto('studentreg/login');
  //}
  if (!$obj['storage']['step'])
    $obj['storage']['step'] = 1;
  $st = $obj['storage']['step'];
  if ($st == 1) {
  //return _student_reg_form6($obj);
  //   return _student_reg_form5($obj);
    return assign_role_form1($obj);
  }
  elseif ($st == 2) {
    return assign_role_form_hod($obj);
  }
  elseif ($st == 3) {
    return assign_role_form_assign_college($obj);
  }
  elseif ($st ==4 ) {
    return assign_role_form_assign_registrar($obj);
  }
  elseif ($st==5) {
    return assign_role_form_assign_hod($obj);
  }
  elseif ($st == 6) {
    return assign_role_form_assign_vc($obj);
  }
  elseif ($st==7) {
    return assign_role_form_assign_bursar($obj);
  }
}

function assign_role_form_assign_bursar(&$obj) {

  $query ="select * from {veritas_staff} where staff_id = '". arg(2) ."'";
  $result = db_query($query);
  //echo  "select * from student where jambno = '".$form['#post']['jamb_no']."' and Admitted = 'Yes'" ; die ;
  $data = db_fetch_object($result);
  $form['staff_id'] = array(
    '#type' => 'hidden',
    '#title' => 'Role',
    '#default_value' => $data->staff_id,
    '#required' => TRUE
  );
  $form['staff_parent'] = array(
    '#type' => 'select',
    '#title' => 'Bursar',
    '#options' => staff_parents($data->role_id),
    '#required' => TRUE
  );
  $form['jambsubp'] = array('#id' => 'edit-previous', '#value' => 'Previous', '#type' => 'submit');
  $form['jambsubn'] = array('#id' => 'edit-next', '#value' => 'Submit', '#type' => 'submit');
  return $form; 
}

function assign_role_form_assign_vc(&$obj) {
 
  $query ="select * from {veritas_staff} where staff_id = '". arg(2) ."'";
  $result = db_query($query);
 //echo  "select * from student where jambno = '".$form['#post']['jamb_no']."' and Admitted = 'Yes'" ; die ;
  $data = db_fetch_object($result);
  $form['staff_id'] = array(
    '#type' => 'hidden',
    '#title' => 'Role',
    '#default_value' => $data->staff_id,
    '#required' => TRUE
  );
  $form['staff_parent'] = array(
    '#type' => 'select',
    '#title' => 'VC', 
    '#options' => staff_parents($data->role_id),
    '#required' => TRUE
  );
  $form['jambsubp']=array('#id' => 'edit-previous', '#value' => 'Previous', '#type' => 'submit');
  $form['jambsubn']=array('#id' => 'edit-next', '#value' => 'Submit', '#type' => 'submit'); 
  return $form; 
}

function assign_role_form_assign_registrar(&$obj) {
  $query ="select * from {veritas_staff} where staff_id = '". arg(2) ."'";
  $result = db_query($query);
 //echo  "select * from student where jambno = '".$form['#post']['jamb_no']."' and Admitted = 'Yes'" ; die ;
  $data = db_fetch_object($result);
  $form['staff_id'] = array(
    '#type' => 'hidden',
    '#title' => 'Role',
    '#default_value' => $data->staff_id,
    '#required' => TRUE
  );
  $parent = staff_parents($data->role_id);
  foreach ($parent as $key => $value) {
    $parent_id = $key;
  }
  $form['staff_parent'] = array(
    '#type' => 'hidden',
    '#title' => 'Registrar', 
    '#required' => TRUE ,
    '#default_value' => $parent_id
  );
  $form['staff_college'] = array(
    '#type' => 'select',
    '#options' => find_college(),
    '#title' => 'Assign College',
    '#default_value' => $data->assigned_college,
    '#required' => TRUE 
  );
  $form['jambsubp'] = array('#id' => 'edit-previous', '#value' => 'Previous', '#type' => 'submit');
  $form['jambsubn'] = array('#id' => 'edit-next', '#value' => 'Submit', '#type' => 'submit');
  return $form;
}
function assign_role_form_assign_hod(&$obj) {
  $query ="select * from {veritas_staff} where staff_id = '". arg(2) ."'";
  $result = db_query($query);
 //echo  "select * from student where jambno = '".$form['#post']['jamb_no']."' and Admitted = 'Yes'" ; die ;
  $data = db_fetch_object($result); 
  $form['staff_id'] = array(
    '#type' => 'hidden',
    '#title' => 'Role',
    '#default_value' => $data->staff_id,
    '#required' => TRUE
  );
  $form['staff_parent'] = array(
    '#type' => 'select',
    '#title' => 'Hod', 
    '#options' => staff_parents($data->role_id),
    '#required' => TRUE
  );
  $form['jambsubp'] = array('#id' => 'edit-previous', '#value' =>  'Previous', '#type' =>  'submit');
  $form['jambsubn'] = array('#id' => 'edit-next', '#value' =>  'Submit', '#type' =>  'submit');
  return $form;  
}

function assign_role_form_assign_college(&$obj) {
 //print_R($obj['storage']['values'][1]['staff_id']);
  $query ="select * from {veritas_staff_college} where staff_id = '". arg(2) ."'";
  $result = db_query($query);
  $data = db_fetch_object($result);
  $form['staff_college'] = array(
   '#type' => 'select',
   '#options' => find_college(),
   '#title' => 'Assign College',
   '#default_value' => $data->assigned_college,
   '#required' => TRUE 
  );
  $form['jambsubp'] = array('#id' => 'edit-previous', '#value' => 'Previous', '#type' => 'submit' , '#default_value' => $data->staff_type_id);
  $form['jambsubn'] = array('#id' => 'edit-next', '#value' => 'Submit', '#type' => 'submit');
  return $form;
}

function assign_role_form1(&$obj) {
  
  $query ="select * from {veritas_staff} where staff_id = '". arg(2) ."'";
  $result = db_query($query);
 //echo  "select * from student where jambno = '".$form['#post']['jamb_no']."' and Admitted = 'Yes'" ; die ;
  $data = db_fetch_object($result);
  $form['#title'] = t('Assign role');
  $form['staff_type'] = array(
    '#type' => 'select',
    '#options' => staff_type(),
    '#title' => 'Staff Type',
    '#default_value' => $data->staff_type_id
  );
  $form['employment_type'] = array(
   '#type' => 'select',
   '#options' => employment_type(),
   '#title' => 'Employment Type',
   '#default_value' => $data->employment_type_id 
  );
  $form['staff_number'] = array(
    '#title' => 'Staff Number',
    '#type' => 'textfield',
    '#size' => 20,
    '#required' => TRUE,
    '#default_value' => $data->staff_no
  );
  $form['staff_position'] = array(
    '#type' =>  'select',
    '#options' => staff_position(),
    '#title' => 'Position',
    '#default_value' => $data->position_id 
  );
  $form['staff_tax_number'] = array(
    '#title' => 'Tax Number',
    '#type' => 'textfield',
    '#size' => 20,
    '#required' => TRUE,
    '#default_value' => $data->tax_number
  );
  $form['staff_department'] = array(
    '#type' => 'select',
    '#options' => department(),
    '#title' => 'Department',
    '#default_value' => $data->department_id
  );
  $form['staff_room'] = array(
    '#title' => 'Room',
    '#type' => 'textfield',
    '#size' => 20,
    '#required' => TRUE,
    '#default_value' => $data->room_number
  );
  $form['salary_garde_level'] = array(
    '#type' => 'select',
    '#options' => salary_grade(),
    '#title' => 'Salary Grade Level',
    '#default_value' => $data->grade_level_id
  );
  $form['appointment_date'] = array(
    '#type' => 'date',
    '#title' => 'Appointment date',
    '#default_value' => $data->appointment_date
  );
  $form['assumption_date'] = array(
    '#type' => 'date',
    '#title' => 'Assumption  date',
    '#default_value' => $data->assumption_date
  );
  $form['ressumption_date'] = array(
    '#type' => 'date',
    '#title' => 'Ressumption  date',
    '#default_value' => $data->resumption_date
  );
  $form['bank'] = array(
    '#type' => 'select',
    '#options' => staff_banks(),
    '#title' => 'Bank',
    '#default_value' => $data->bank_id
   );
  $form['account_number'] = array(
    '#title' => 'Account Number',
    '#type' => 'textfield',
    '#size' => 20,
    '#required' => TRUE,
    '#default_value' => $data->account_id
  );     
  $form['staff_role'] = array(
    '#type' => 'select',
    '#options' => staff_roles(),
    '#title' => 'Role',
    '#default_value' => $data->role_id,
    '#required' => TRUE 
  );
  $form['staff_id'] = array('#type' => 'hidden', '#title' => 'Role', '#default_value' => $data->staff_id, '#required' => TRUE);
  $form['user_id']=array('#type' =>  'hidden', '#title' => 'Role', '#default_value' => $data->user_id, '#required' => TRUE);
  // $form['jambsubp']=array('#id' =>  'edit-previous','#value' =>  'Previous','#type' =>  'submit','#default_value'=>$data->staff_type_id);
  $form['jambsubn']=array('#id' => 'edit-next', '#value' => 'Submit', '#type' => 'submit');
  return $form;
}

function assign_role_form_hod(&$obj) {
  $query ="select * from {veritas_staff} where staff_id = '". arg(2) ."'";
  $result = db_query($query);
 //echo  "select * from student where jambno = '".$form['#post']['jamb_no']."' and Admitted = 'Yes'" ; die ;
  $data = db_fetch_object($result);
  $form['staff_id'] = array('#type' => 'hidden', '#title' => 'Role', '#default_value' => $data->staff_id, '#required' => TRUE);
  $form['staff_parent'] = array('#type' => 'select', '#title' => 'Dean', '#options' => staff_parents($data->role_id), '#required' => TRUE);
   /*$form['staff_parent']=array('#type' =>  'select','#title' =>  'Dean', 
'#ahah'=>array('event' =>  'change','wrapper' =>  'department_id','path' =>  'dean_department','method' =>  'html') ,'#options'=>staff_parents($data->role_id),'#required'=>TRUE);*/
  $form['staff_department']=array('#type' => 'hidden', '#default_value' => $data->department_id);
  $form['jambsubp']=array('#id' => 'edit-previous', '#value' => 'Previous', '#type' => 'submit');
  $form['jambsubn']=array('#id' => 'edit-next', '#value' => 'Submit', '#type' => 'submit');
  return $form;
}

function dean_department() {
  $n = 'staff_department';
    $div = 'div-id-co1';
  $d = (int)$_POST['staff_parent'];
    $f = array();
    $query = sprintf("select d.* from {department} d inner join {veritas_staff_college} sc on d.college_id = sc.assigned_college where sc.staff_id=%d" , $d);
  $r = db_query("select * from {department} d inner join {veritas_staff_college} sc on d.college_id = sc.assigned_college where sc.staff_id=%d" , $d);
  $f[] = 'Select';
    
  while ($s = db_fetch_object($r))
    $f[$s->department_id] = $s->department_name;
        
  $form = array(
    '#type' => 'select',
    '#title' => 'Department',
    '#options' => $f,
    '#required' => TRUE
  );
    $output = _student_ahah_render($form , $n);
  print drupal_to_js(array('data' => $output, 'status' => TRUE));
  exit();
}
function staff_parents($role = 0) {
 
  $query = "select s.* from {veritas_staff} s inner join {veritas_staff_role} sr on sr.parent_id = s.role_id and  sr.id='". $role ."'";
  $r = db_query($query);
  $titles = array();
  $titles[] = "Select";
  while ($f = db_fetch_object($r))
    $titles[$f->staff_id] = $f->staff_first_name;
  return $titles;
}

function superadmin_perm() {
   
      return array('superadmin register login');


}

function superadmin_access() { 
  return TRUE;
}

function superadmin_user($op, &$edit, &$account, $category) {
  switch ( $op ) {
    case 'validate':
     $query = "Select * from {role} where name='Superadmin'";
     $r = db_query($query);
     $f = db_fetch_object($r);
     if ( $category == 'account' && ! $account->uid && in_array($f->rid , $edit['roles']) ) {
       if ( ! check_role($f->rid) ) {
        form_set_error('role', 'Superadmin already exists');
       }
     }
          else {
       if ($category == 'account' && $account->uid && in_array($f->rid , $edit['roles']) ) {
         if ( ! check_role($f->rid, $account->uid ) ) {
           form_set_error('role', 'Superadmin already exists');
         }
       }
     }
    //die ;
   break;
   case 'login':
      if (in_array('Superadmin', $account->roles)) {
         unset($_SESSION['staff']);
         unset($_SESSION['student']);
         unset($_SESSION['veritas']);
         $_SESSION['veritas']['superadmin']['data'] = $account;
      }
   break;
  }
 }

function check_role($rid , $user_id) {
  
  if ($user_id !=  "") {
    $where = " where u.uid <> ". $user_id ."  and ur.rid=". $rid;
  }
    else {
     $where = " where ur.rid=". $rid;
  }
  $query = "select count(*) as count from {users} u  left join {users_roles} ur on u.uid = ur.uid  ". $where;
  $r = db_query($query);
  $f = db_fetch_object($r);
  return ($f->count == 0);
 }

function superadmin_login_form(&$obj) {
 
  unset($_SESSION['staff']);
  unset($_SESSION['student']);
  unset($_SESSION['veritas']);
 /*echo md5('superadmin');
 $drupal_data = array(
    'mail' =>  'superadmin',
    'pass' =>  'superadmin',
    'name' =>  'superadmin',
    'roles'=>array(11),
    'init'=>$_SESSION['student']['data']->email_address,
    'status'=>1
    
   );
   $user = user_save(NULL,$drupal_data);*/
  $form['#title'] = t('Superadmin Login');
  $form['username'] = array('#title' => 'Username', '#type' => 'textfield', '#size' => 20, '#required' => TRUE);
  $form['password'] = array('#type' => 'password', '#title' => 'Password', '#size' => '30');
  $form['submit'] = array('#value' => 'Login', '#type' => 'submit');
  return $form;
}

function superadmin_login_form_validate($form, &$states) {
 
   $query = "select * from {veritas_superadmin} where username = '". $form['#post']['username'] ."'";
 //echo  "select * from student where jambno = '".$form['#post']['jamb_no']."' and Admitted = 'Yes'" ; die ;
  $result = db_query($query);
  if ($result && mysql_num_rows($result) > 0) {
    $data = db_fetch_object($result);
    if ($form['#post']['password'] == $data->password) {
       $_SESSION['veritas']['superadmin']['data'] = $data;
    }
        else {
       form_set_error('passoword', "Password is not correct.");
    }
  }
    else {
    form_set_error('username', "Username is not valid.");
  }
}

function superadmin_login_form_submit(&$obj) {
  drupal_goto('superadmin/stafflist');
}

function su_staff_search_form(&$obj) {
  $form = array(
    '#theme' => 'form_panel_table',
    '#form_panel_table_attributes' => array('border' => 0),
        '#redirect' => FALSE
    );
  $form['staff_no'] = array('#title' => 'Staff Number',
     '#type' => 'textfield',
     '#size' => 20,
     '#default_value' => $data->staff_no, 
     '#form_panel_col' => 1,
     '#form_panel_row' => 1
    );
 
  $form['staff_last_name'] = array(
      '#title' => 'Lastnamme',
        '#type' => 'textfield',
        '#size' => 20,
        '#default_value' => $data->staff_no ,
        '#form_panel_col' => 2,
        '#form_panel_row' => 1
    );
  $form['jambsubn'] = array('#id' => 'edit-next', '#value' => 'Search', '#type' => 'submit', '#form_panel_col' => 3, '#form_panel_row' => 1);
  return $form;
 
}

function staff_list() {
 
   ob_start();
  echo  drupal_get_form('su_staff_search_form');

  if (isset($_POST['staff_no'])) {
    su_staff_search_list();
  }
  return ob_get_clean();
}

function su_staff_search_list() {
  if (!isset($_SESSION['veritas']['superadmin'])) {
    drupal_goto('superadmin/login');
  }
  $search_keys = array('staff_no', 'staff_last_name');
  $search_values = array('gender' => '', 'department_id', 'staff_type_id', 'grade_level_id', 'state');
  $data = array_filter($_POST);
  $condition = array();
  foreach ($search_keys as $value) {
    if (isset($data[$value])) {
      $condition[] = "s.". $value ."='". $data[$value] ."'";
    }
  }
  if (implode(' and ', $condition) !='') {
     $condition = " where ". implode(' and ', $condition);
  }
    else {
   $condition  = '';
  }
    $query = "Select  s.* , sr.name as role_name from {veritas_staff} s left join {veritas_staff_role} sr on sr.id = s.role_id ". $condition;
  $result = db_query($query);
  ?>
  <table border='1' align='center'>
          <tr bgcolor='#ACCFCC'><td colspan='7'><b>Staff List</b></td></tr>
          <tr><td><b>Last Name</b></td><td><b>Middle Name</b></td><td><b>First Name</b></td><td><b>Role</b></td><td><b>Username</b></td><td><b>Password</b></td><td><b>Action</b></td></tr>
     <?php
        while ($f = db_fetch_object($result)) {
        
     ?>
       <tr>
           <td><?php echo $f->staff_last_name; ?></td>
           <td><?php echo $f->staff_middle_name; ?></td>
           <td><?php echo $f->staff_first_name; ?></td>
            <td><?php echo $f->role_name; ?></td>
            <td><?php echo $f->usrname; ?></td>
            <td><?php echo $f->password; ?></td>
           <td><a href="<?php echo url('superadmin/assignrole/'. $f->staff_id)?>">Assign Role</a></td>
          
           
 </tr>
    <?php
       }
    ?>
</table> 
<?php
}
