<?php
/*
 * @author Kayode Odeyemi
 * Installs eduerp_transaction module
 */


/**
 * Implementation hook_install
 *
 * @author Kayode Odeyemi (dreyemi@gmail.com)
 */
function eduerp_transaction_install() {
    drupal_set_message('Eduerp Transaction is installed');
}

/**
 * Implementation hook_uninstall
 *
 * @author Kayode Odeyemi (dreyemi@gmail.com)
 */
function eduerp_transaction_uninstall() {
    drupal_set_message('Eduerp transaction has been uninstalled successfully');
}
