<?php
include_once(dirname(__FILE__) . '/../permissions_api.module');

// staff module installation

/**
 * initialize the permissions for roles in this module
 */
function staff_perms_initialize() {
  $permissions = array(
    'Staff' => array(
      // 'create staff_profile content',
      'edit own staff_profile content',

      'edit field_profile_room',
      'edit field_profile_temporary_address',
      'edit field_profile_temporary_city',
      'edit field_profile_temporary_state',

      'view field_profile_staff_no',
      'view field_profile_employment_type',
      'view field_profile_staff_type',
      'view field_profile_room',
      'view field_profile_appointment_date',
      'view field_profile_temporary_address',
      'view field_profile_temporary_city',
      'view field_profile_temporary_state',

      'staff department list',
      'staff view lecturer',
      'staff register course',
      'staff list',
      'student list students',
      'staff assign role',
      'view grading',
      'edit any student_grades content',
      'staff register',

      'edit field_ca1',
      'edit field_ca2',
      'edit field_ca3',
      'edit field_ca4',
      'edit field_comment_grades',
      'edit field_exam_score',

      'view field_ca1',
      'view field_ca1forstudent',
      'view field_ca1locked',
      'view field_ca2',
      'view field_ca2forstudent',
      'view field_ca2locked',
      'view field_ca3',
      'view field_ca3forstudent',
      'view field_ca3locked',
      'view field_ca4',
      'view field_ca4forstudent',
      'view field_ca4locked',
      'view field_exam_score',
      'view field_examscoreforstudent',
      'view field_examscorelocked',
      'view field_calc_type',
      'view field_cgpa_sp',
      'view field_cgpaforstudent_sp',
      'view field_code',
      'view field_college_abbreviation',
      'view field_college_id',
      'view field_college_name',
      'view field_college_email_subdomain',
      'view field_comment_gpa',
      'view field_comment_grades',
      'view field_comment_sp',
      'view field_course_description',
      'view field_course_id',
      'view field_course_instance',
      'view field_coursecode',
      'view field_coursetitle',
      'view field_credit_load_completed',
      'view field_credit_load_completed_sp',
      'view field_credit_load_registered',
      'view field_creditload',
      'view field_department_id',
      'view field_department_name',
      'view field_department_code',
      'view field_department_nid',
      'view field_dropped',
      'view field_duration',
      'view field_gpa',
      'view field_gpaforstudent',
      'view field_gptotal',
      'view field_gptotal_sp',
      'view field_grade',
      'view field_gradeforstudent',
      'view field_gradepoint',
      'view field_gradepointforstudent',
      'view field_credit_load_sg',
      'view field_lecturer',
      'view field_lecturer_alternate',
      'view field_level',
      'view field_level_name_gpa',
      'view field_location',
      'view field_mat_no',
      'view field_max_duration',
      'view field_min_credit_load_program',
      'view field_prerequisite',
      'view field_prerequisite_codes',
      'view field_program_ref_gpa',
      'view field_program_ref_sp',
      'view field_program_type',
      'view field_programme',
      'view field_programme_abbr',
      'view field_programme_name',
      'view field_repeat',
      'view field_semester',
      'view field_semester_name',
      'view field_semester_name_gpa',
      'view field_sess_name',
      'view field_sess_name_gpa',
      'view field_student_gpa',
      'view field_student_program_ref_gpa',
      'view field_student_ref_gpa',
      'view field_student_ref_sp',
      'view field_timetable',
      'view field_total_score',
      'view field_totalscoreforstudent',

      'view field_profile_matno',
      'view field_profile_jambno',
      'view field_profile_mode_of_entry',
      'view field_profile_score_details',
      'view field_profile_mode_of_study',
      'view field_profile_yearofentry',
      'view field_profile_reg_session',
      'view field_profile_reg_semester',
      'view field_profile_level_name',
      'view field_profile_first_choice',
      'view field_profile_hobbies',
      'view field_profile_sponsor_name',
      'view field_profile_sponsor_address',
      'view field_profile_sponsor_city',
      'view field_profile_sponsor_state',
      'view field_profile_sponsor_phone',
      'view field_profile_sponsor_mobile',
      'view field_profile_sponsor_email',
      'view field_profile_state_sponsor',
      'view field_profile_exam_number_1',
      'view field_profile_exam_number_2',
      'view field_profile_year_exam_taken_1',
      'view field_profile_year_exam_taken_2',
      'view field_profile_health_status',
      'view field_profile_health_disability',
      'view field_profile_kin_address',
      'view field_profile_kin_city',
      'view field_profile_kin_mobile',
      'view field_profile_kin_name',
      'view field_profile_kin_relationship',
      'view field_profile_kin_telephone',
      'view field_profile_kin_title',
      'view field_profile_olevel_exams_1',
      'view field_profile_olevel_insti1',
      'view field_profile_olevel_qual_1',
      'view field_profile_olevel_exams_2',
      'view field_profile_olevel_insti2',
      'view field_profile_olevel_qual_2',
      'view field_university_email',
      'view field_personal_email',
    ),

    'Registry' => array(
      'staff data',
      'student clearance',
      'student data',
      'audit approvals',
      'access user profiles',

      'view field_clearance_date',
      'view field_staff_clearance',
      'view field_staff_verification',
      'view field_student',
      'view field_verification_date',
      'view field_clearance_uncleared',
      'view field_deferred',
      'view field_uncleared_reasons',

      'view field_url',
      'view field_approver',
      'view field_destination',
      'view field_department1',
      'view field_college1',
      'view field_level1',
      'view field_session1',
      'view field_semester1',
      'view field_location1',
      'view field_what_approved',
      'view field_action',

      'view field_student_ref_sr',
      'view field_event_sr',
      'view field_degree_sr',
      'view field_session_sr',
      'view field_student_program_sr',
      'view field_approver_sr',
      'view field_comment_sr',
    ),

    'Bursary' => array(
      'staff data',
      'student payments',
      'access user profiles',
      'view all orders',
    ),

    'SA' => array(
      'student data',
      'hostel_allocation admin',
    ),
  );

  return $permissions;
}

function staff_install() {
  drupal_set_message('staff module installed');
}

function staff_enable() {
  // Install the content types
  $staff_profile_content_type = file_get_contents(dirname(__FILE__) . '/cck/cck_staff_profile.txt');

  // determine replacement or new installation of content type
  $staff_profile_info = content_types('staff_profile');
  $is_new = (is_array($staff_profile_info) && array_key_exists('type', $staff_profile_info)) ? false : true;

  $form_state = array(
    'values' => array(
      'type_name' => ($is_new) ? '<create>' : 'staff_profile',
      'macro' => $staff_profile_content_type,
    ),
  );
  drupal_execute('content_copy_import_form', $form_state);
  content_clear_type_cache();

  // create staff role
  permissions_create_role('Staff');
  permissions_create_role('Registry');
  permissions_create_role('Bursary');
  permissions_create_role('SA');

  // set content type permissions
  $perms = staff_perms_initialize();

  foreach ($perms as $role => $permissions) {
    permissions_grant_permissions($role, $permissions);
  }
}

function staff_uninstall() {
  drupal_set_message('staff module uninstalled');
}

function staff_disable() {
  // remove content type permissions
  $perms = staff_perms_initialize();

  foreach ($perms as $role => $permissions) {
    permissions_revoke_permissions($role, $permissions);
  }
}
?>
