<?php

/**
 * Ubercart integration of EduERP fees
 *
 * @author Kayode Odeyemi (dreyemi@gmail.com)
 */

define('EDUERP_FEES_NORMAL', 'fees');
define('EDUERP_FEES_HOSTEL', 'hostel');
define('FEES_PAID', 'payment_received');
define('FEES_PENDING', 'pending');
define('HAS_SCHOLARSHIP', 1);
define('FEES_FULL', 'Full Amount');
define('FEES_FIRST_INSTALMENT', 'Instalment1');
define('FEES_SECOND_INSTALMENT', 'Instalment2');


/**
 * Implementation of hook_menu(), called to generate menus when module setup at admin/build/modules is saved
 */
function uc_eduerp_fees_menu() {
  $items['edupay/callback'] = array(
    'title' => 'Process EduPay Callback',
    'page callback' => 'uc_eduerp_fees_update_fees',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  $items['edupay/displaycart'] = array(
    'title' => 'Student Fees Due to be Paid',
    'page callback' => 'display_cart_for_scholarship',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}


/**
 * Disable UberCart Orders Tab for Users
 */
function uc_eduerp_fees_menu_alter(&$items) {
  $items['user/%user/orders'] = MENU_CALLBACK;
  unset($items['user/%user/orders']);
}


/**
 * Handles 'edupay/callback' menu callback to handle POST from EduPay Server to indicate Payment Received or Cancelled for an Invoice, returning JSON packet to EduPay
 * @uses hostel_allocation_allocate_bedspace()
 * @uses hostel_allocation_revoke_expired_reservation()
 */
function uc_eduerp_fees_update_fees() {
  $order_id = $_POST['order_id'];
  $status = $_POST['status'];
  $uid = $_POST['uid'];
  $transaction_token = $_POST['transaction_token'];
  $bank_username = $_POST['bank_username'];
  if (empty($bank_username)) $bank_username = ' ';

  if ($_SERVER['REQUEST_METHOD'] != 'POST' || empty($order_id) || empty($status) || empty($uid) || empty($transaction_token) || ($status != 'payment_received' && $status != 'canceled')) {
    drupal_set_header('HTTP/1.1 404 Not Found');
    $content = new stdClass();
    $content->status = 'fail';
    drupal_json($content);
    exit();
  }

  $transaction_token_found = FALSE;
  $sql = "SELECT op.data FROM {uc_orders} o, {uc_order_products} op
    WHERE
      o.order_id=%d AND
      o.order_status IN ('pending') AND
      o.order_id=op.order_id";
  $result = db_query($sql, $order_id);
  if ($order = db_fetch_array($result)) { // Only need to look at one uc_order_products, transaction_token is in them all
    $data = unserialize($order['data']);
    if ($data['transaction_token'] == $transaction_token) $transaction_token_found = TRUE;
  }

  if (!$transaction_token_found) {
    $content = new stdClass();
    $content->status = 'fail';

    // Status was not expected 'pending', but it might be 'canceled' or 'payment_received'... Give suitable message, these are semi valid conditions
    $sql = "SELECT o.order_status, op.data FROM {uc_orders} o, {uc_order_products} op
      WHERE
        o.order_id=%d AND
        o.order_id=op.order_id";
    $result = db_query($sql, $order_id);
    if ($order = db_fetch_array($result)) {
      $data = unserialize($order['data']);
      if ($order['order_status'] == 'canceled'         && $data['transaction_token'] == $transaction_token) $content->status = 'fail-already-canceled';
      if ($order['order_status'] == 'payment_received' && $data['transaction_token'] == $transaction_token) $content->status = 'fail-already-payment_received';
    }

    drupal_set_header('HTTP/1.1 404 Not Found');
    drupal_json($content);
    exit();
  }

  $sql = "SELECT ctb.field_uc_product_id_nid, op.title
    FROM {content_type_blocks} ctb, {content_type_rooms} ctr, {content_type_room_reservations} ctrr, {uc_order_products} op
    WHERE
      ctb.nid=ctr.field_block_id_nid AND
      ctr.nid=ctrr.field_room_id_nid AND
      ctrr.field_student_id_uid=%d AND
      ctb.field_uc_product_id_nid=op.nid AND
      op.order_id=%d";
  $query_result = db_query($sql, $uid, $order_id);
  if (db_fetch_array($query_result)) {
    $hostel_in_order = TRUE; // Found a hostel reservation which has a product in this order
  }
  else {
    $hostel_in_order = FALSE;
  }

  if ($status == 'payment_received') {
    if ($hostel_in_order) hostel_allocation_allocate_bedspace($uid);

    db_query("UPDATE {uc_orders} set order_status = '$status' WHERE order_id = %d", $order_id);
    db_query("UPDATE {fees_order} SET status = '$status' WHERE order_id = %d", $order_id);
    $timestamp = time();
    db_query("UPDATE {fees_order} SET expiry_date = %d WHERE order_id = %d", $timestamp, $order_id);
    db_query("UPDATE {fees_order} SET email = '%s' WHERE order_id = %d", $bank_username, $order_id);
    watchdog('uc_eduerp_fees', t('Fees item in cart with order_id of @order_id has been successfully paid for by @uid', array('@order_id' => $order_id, '@uid' => $uid)));
  }

  if ($status == 'canceled') {
    if ($hostel_in_order) hostel_allocation_revoke_expired_reservation($uid);

    db_query("UPDATE {uc_orders} set order_status = '$status' WHERE order_id = %d", $order_id);
    db_query("UPDATE {fees_order} SET status = '$status' WHERE order_id = %d", $order_id);
    watchdog('uc_eduerp_fees', t('Fees item in cart with order_id of @order_id of user @uid has been canceled', array('@order_id' => $order_id, '@uid' => $uid)));
  }

  $content = new stdClass();
  $content->status = 'success';
  drupal_json($content);
  exit();
}


/**
 * Return HTML for Display of Fees that a Student is due to Pay (to be used for Scholarship authorisation purposes), also add Student data
 *
 * @uses show_cart_for_student()
 * @return string HTML
 */
function display_cart_for_scholarship() {
  global $user;

  ob_start();

  $student_profile = new UserProfile($user->uid);

  $studentname = '';
  if (!empty($student_profile->profile_first_name) && !empty($student_profile->profile_last_name)) {
    $middle = '';
    if (!empty($student_profile->profile_middle_name)) $middle = ' ' . $student_profile->profile_middle_name;
    $studentname = "{$student_profile->profile_last_name}, {$student_profile->profile_first_name}{$middle}";
  }

  $sql = "SELECT field_programme_name_value FROM {content_type_program} WHERE nid=%d";
  $result = db_query($sql, $student_profile->profile_first_choice);
  $row = db_fetch_object($result);

  ?>
  <br />
  <h2><?php echo variable_get('eduerp_institution_current', '') ?></h2>
  <?php echo variable_get('eduerp_institution_address', '') ?><br />
  <br />
  <h3>Name: <?php echo $studentname ?><br />
  Admission Number: <?php echo $user->name ?></h3><br />
  Session: <?php echo variable_get('eduerp_current_session', '') ?><br />
  Programme: <?php echo $row->field_programme_name_value ?><br />
  <br />
  If you are due a scholarship, print and bring this page to the Scholarship Board.<br /><br />
  <?php if (FALSE) { ?>(<a href="/print/edupay/displaycart">Click here for a Printer-friendly version</a> which can be used to generate a better printout.)<br /><br /><?php } ?>

  <table border='1' align='center'  cellpadding="5" cellspacing="5">
    <tr bgcolor='#ACCFCC'><td><b>Fees for <?php echo "$studentname for " . variable_get('eduerp_current_session', ''); ?></b></td></tr>
    <tr>
      <td><?php echo show_cart_for_student(); ?></td>
    </tr>
  </table>
<?php
  return ob_get_clean();
}


/**
 * Return HTML for Display of School Fees that a Student is due to Pay (to be used for Scholarship authorisation purposes)
 *
 * @return string HTML
 */
function show_cart_for_student() {
  $subtotal = 0;

  // Set up table header.
  $header = array(
    array('data' => t('Products'), 'class' => 'products'),
    array('data' => t('Price'), 'class' => 'price'),
  );

  $context = array();

  // Set up table rows.
  $contents = uc_cart_get_contents();
  foreach ($contents as $item) {
    $description = uc_product_get_description($item);
    if (!empty($description) && strpos($description, 'Fee Structure') !== FALSE) { // Don't include e.g. Hostels
      $total = $item->price;
      $subtotal += $total;

      $description = check_plain($item->title) . $description;

      // Remove node from context to prevent the price from being altered.
      $context['revision'] = 'themed-original';
      $context['type'] = 'amount';
      unset($context['subject']);
      $rows[] = array(
        array('data' => $description, 'class' => 'products'),
        array('data' => uc_price($total, $context), 'class' => 'price'),
      );
    }
  }

  // Add the subtotal as the final row.
  $context = array(
    'revision' => 'themed-original',
    'type' => 'amount',
  );
  $rows[] = array(
    'data' => array(array('data' => '<span id="subtotal-title">' . t('Total:') . '</span> ' . uc_price($subtotal, $context), 'colspan' => 2, 'class' => 'subtotal')),
    'class' => 'subtotal',
  );

  return theme('table', $header, $rows, array('class' => 'cart-review'));
}


/**
 * Rebuild the fees items based on order state of payment_received or pending (Not Used)
 *
 * @deprecated
 */
function _uc_eduerp_fees_rebuild_fees_processed($fees, $paid_nid, $preserve_keys = TRUE) {
  foreach($fees as $fee) {
    if($fee['type'] == 'fees') {
      foreach($fee['item'] as $key => $value){
        //$paid_fees_items[$fee['item']['product_nid']];
        if($paid_nid == $fee['item'][$key]['product_nid']) {
          unset($fee['item'][$key]);
          //if all fees items have been paid for
          if(is_null($fee['item'])){
            unset($fees['fees']);
          }
        }
      }
    }
    if($fee['type'] == 'hostel') {
      if($paid_nid == $fee['item']['product_nid']) {
        unset($fees['hostel']);
      }
    }
  }
  return ($preserve_keys === TRUE) ? $fees : array_shift($fees);
}


/**
 * Remove any 'pending' or 'payment_received' Fees for a Student so that they only pay for newly added Fee items for the current Session
 *
 * @param int $student_id
 * @param array $fee_items
 * @return array
 */
function uc_eduerp_fees_completed_order_items($student_id, $fee_items) {
  if(is_null($student_id)) return FALSE;

  foreach ($fee_items['fees']['item'] as $i => $item) {
    $sql = "SELECT op.nid, op.data FROM {uc_orders} o, {uc_order_products} op
      WHERE
        o.uid=%d AND
        o.order_status IN ('payment_received', 'pending') AND
        o.order_id=op.order_id AND
        op.nid=%d";
    $result = db_query($sql, $student_id, $item['product_nid']);
    while ($order = db_fetch_array($result)) {
      $data = unserialize($order['data']);
      if ($data['session'] == variable_get('eduerp_current_session', '')) {
        if (isset($item['option_id'])) {
          if ($item['attribute_id'] == $data['attribute_id'] && $item['option_id'] == $data['option_id']) {
            unset($fee_items['fees']['item'][$i]);
            unset($fee_items['fees']['description'][$i]);
          }
        }
        else {
          unset($fee_items['fees']['item'][$i]);
          unset($fee_items['fees']['description'][$i]);
        }
      }
    }
  }

  if (empty($fee_items['fees']['item'])) unset($fee_items['fees']);

  if (empty($fee_items['hostel']['item'])) {
    unset($fee_items['hostel']);
  }
  else {
    $sql = "SELECT op.nid, op.data FROM {uc_orders} o, {uc_order_products} op
      WHERE
        o.uid=%d AND
        o.order_status IN ('payment_received', 'pending') AND
        o.order_id=op.order_id AND
        op.nid=%d";
    $result = db_query($sql, $student_id, $fee_items['hostel']['item']['product_nid']);
    while ($order = db_fetch_array($result)) {
      $data = unserialize($order['data']);
      if ($data['session'] == variable_get('eduerp_current_session', '')) {
        unset($fee_items['hostel']);
      }
    }
  }

  return $fee_items;
}


/**
 * Not used
 *
 * @deprecated
 */
function user_has_completed_order_items($student_id) {
  $status_paid = FEES_PAID;
  $status_pending = FEES_PENDING;
  $result = db_query("SELECT order_id, data FROM {uc_orders} WHERE uid = %d and order_status IN ('%s', '%s') and data IS NOT NULL", $student_id, $status_paid, $status_pending);
  //db_affected_rows is unreliable. see: http://api.drupal.org/api/drupal/includes--database.pgsql.inc/function/db_affected_rows/6
  return (db_affected_rows() > 0)? TRUE : FALSE;
 }


/**
 * Handles 'user/%/fees/pay'/Pay fees menu for a Student to start the Fees Payment process
 *
 * <p>Find the Fees Setup for a Student and generate a list of Fees due (including any Hostel Payment).</p>
 * <p>Ensure the Student is eligible to Pay Fees.</p>
 * <p>Remove any pending or paid fees.</p>
 * <p>Generate a form which stores all this fee data.</p>
 * <p>Allow the Student to deselect the Hostel Payment for now.</p>
 * @uses uc_eduerp_fees_pay_fees_form_submit()
 * @uses uc_eduerp_fees_eduerp_fees()
 * @uses is_fee_setup_existing_for_student()
 * @uses student_clearance_performed()
 * @uses student_next_level()
 * @uses uc_eduerp_fees_completed_order_items()
 * @uses is_reservation_existing()
 * @param array $form_state
 * @param int $student_id This Parameter is generated when module setup at admin/build/modules is saved and is always wrong (it is the user who enabled the module)!
 * @return array Drupal Form
 */
function uc_eduerp_fees_pay_fees(&$form_state, $student_id) {
  global $user;
  $student_id = $user->uid;

  db_query('INSERT IGNORE INTO {student_semaphore} VALUES (%d, 0, 0)', $student_id); // Only inserts if does not already exist

  $row = db_fetch_object(db_query('SELECT semaphore_timestamp FROM {student_semaphore} WHERE uid=%d', $student_id));
  if (time() > ($row->semaphore_timestamp + 10)) {
    // Unlock the Semaphore if 10 seconds have passed
    db_query('UPDATE {student_semaphore} SET semaphore_value=0 WHERE uid=%d', $student_id);
  }

  uc_cart_empty($student_id);

  module_load_include('inc', 'student', 'student.rules');
  $form = array();

  // Should really be a call to uc_eduerp_fees_eduerp_fees(), no need for a hook
  if($fees_items = module_invoke('uc_eduerp_fees', 'eduerp_fees')) {
    $fees = $fees_items;
  }

  // Check if the current user has an existing fees setup
  if(!is_fee_setup_existing_for_student($student_id)) {
    drupal_set_message(t("Sorry, you don't have a valid fees setup. Please contact bursary"), 'error');
    return FALSE;
  }

  // A student need to be cleared to progress
  if(!student_clearance_performed($student_id)) {
    $fees = array();
    drupal_set_message(t('Sorry, you need to be cleared to progress'), 'error');
    return FALSE;
  }

  // test if student is still a student (graduated or expelled)
  $session = variable_get('eduerp_current_session', '') ? variable_get('eduerp_current_session', '') : NULL;
  if(!student_next_level($student_id, $session)){
    $fees = NULL;
    drupal_set_message(t('Sorry. Your student record is no longer eligible to pay fees'), 'error');
    return FALSE;
  }

  // Remove any pending or paid fees...
  $fees = uc_eduerp_fees_completed_order_items($student_id, $fees);

  if (empty($fees['fees']['item']) && empty($fees['hostel'])) {
    $message = 'All your fees items are currently in process or already paid for. Consult the bursary.';

    $rs = db_query("SELECT order_id, order_status FROM {uc_orders} WHERE uid=%d AND order_status IN ('payment_received', 'pending')", $user->uid);
    $firstone = TRUE;
    while ($r = db_fetch_object($rs)){
      if ($firstone) {
        $message .= '<br />You may regenerate your invoices by clicking on them (and bring to bank if you have not already done so)...';
        $firstone = FALSE;
      }
      $message .= '<br /><a href="' . url('user/' . $user->uid . '/order/' . $r->order_id . '/invoice/print') . '" target="_blank">Invoice: ' . $r->order_id . '</a> (' . $r->order_status . ')';
    }
    drupal_set_message($message, 'error');
    return FALSE;
  }

  if(!is_reservation_existing($student_id)) {
    unset($fees['hostel']);
  }

  $form['eduerp_fees'] = array(
    '#type' => 'fieldset',
    '#title' => t('Pay fees'),
    '#collapsible' => TRUE,
  );
  $form['eduerp_fees']['uid'] = array(
    '#type' => 'hidden',
    '#value' => $student_id
  );
  foreach($fees as $fee){
    $type = $fee['type'];
    $description = $fee['description'];
    $options = $fee['options'];
    $options_nid = (string)$options['nid'];

    if($type == EDUERP_FEES_NORMAL) {
      foreach($fee['item'] as $key => $value){
        $nids[$key] = $value['product_nid'];
        $items[$key] = $value;
        $desc[$key] = $value['item_description'];

        $form['eduerp_fees']["$type_$key"] = array(
          '#type' => 'checkbox',
          '#title' => strip_tags($desc[$key]),
          '#default_value' => TRUE,
          '#disabled' => TRUE //($type == 'fees')
        );

      }
      // construct fees hidden fields separately
      foreach($nids as $nid) {
        $form['eduerp_fees'][$type . '_' . $nid] = array(
          '#type' => 'hidden',
          '#value' => $nid,
        );
      }

      foreach($items as $item) {
        // foreach of the fees item description, parse it to extract the extras
        $key_search = $item['item_description'];
        if(!is_null($key_search)) {
          preg_match_all('/Full Amount|Instalment1|Instalment2/', $key_search, $matches);
          foreach($matches as $key => $value) {
            $item['extras']['fees_payment_format'] = $value;
            break;
          }
        }

        $id = $item['product_nid'];
        $form['eduerp_fees']['product_item_' . $type . '_' . $id] = array(
          '#type' => 'hidden',
          '#value' => $item,
        );
      }
      $form['eduerp_fees']['options_' . $type. '_' . $options_nid] = array(
        '#type' => 'hidden',
        '#value' => $options,
      );
    }

    // Do the rest of the things for hostel
    if($type == EDUERP_FEES_HOSTEL) {
      $item = $fee['item'];
      $nid = $fee['item']['product_nid'];

      // Build a checkbox
      $form['eduerp_fees'][$type] = array(
        '#type' => 'checkbox',
        '#title' => strip_tags($description),
        '#default_value' => TRUE,
        '#disabled' => FALSE //($type == 'fees')
      );

      $form['eduerp_fees'][$type . '_' .$nid] = array(
          '#type' => 'hidden',
          '#value' => $nid,
      );
      $form['eduerp_fees']['product_item_' . $type] = array(
          '#type' => 'hidden',
          '#value' => $item,
      );
      $form['eduerp_fees']['options_' . $type. '_' . $options_nid] = array(
          '#type' => 'hidden',
          '#value' => $options,
      );

    }
  }
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Pay Fees (Click Once Only!)')
  );
  $form['#submit'][] = 'uc_eduerp_fees_pay_fees_form_submit';

  return $form;
}


/**
 * submit hook for {@link uc_eduerp_fees_pay_fees_form()} to parse the Form data, empty the UberCart Shopping Cart, add items to the Cart and go to UberCart Checkout
 *
 * @uses is_scholarship_authorisation_existing()
 * @uses uc_eduerp_fees_get_profile_items()
 */
function uc_eduerp_fees_pay_fees_form_submit($form, &$form_state) {
  $student_id = $form_state['values']['uid'];

  // This is an issue because cart items can get added in parallel even though the cart will have been cleared (if someone double clicks)
  db_query('UPDATE {student_semaphore} SET semaphore_value=semaphore_value+1, semaphore_timestamp=%d WHERE uid=%d', time(), $student_id);
  $r = db_fetch_object(db_query('SELECT semaphore_value FROM {student_semaphore} WHERE uid=%d', $student_id));
  if ($r->semaphore_value != 1) {
    // Semaphore is locked so redirect
    drupal_set_message('You seem to have clicked on "Pay Fees" more than once, please wait 10 seconds and click "Pay Fees" again once only).', 'error');
    drupal_goto("user/$student_id/fees/pay");
  }

  $values = array();
  foreach($form_state['values'] as $key => $value) {
    $vkeys[] = $key;
    $values[$key] = $value;
  }
  $key_search = implode(',', array_values($vkeys));
  preg_match_all('/product_item_fees_\d+/', $key_search, $matches);
  // match options for fees option
  preg_match_all('/options_fees_\d+/', $key_search, $fees_option_matches);
  // find all hostel keys if it exists
  if(in_array('hostel', $vkeys)) {
    preg_match_all('/product_item_hostel/', $key_search, $hostel_matches);
    preg_match_all('/options_hostel_\d+/', $key_search, $hostel_option_matches);
  }
  $matchs = array(
    'fees' => array_shift($matches),
    'fees_options' => array_shift($fees_option_matches),
    'hostel' => in_array('hostel', $vkeys) ? array_shift($hostel_matches) : array(),
    'hostel_options' => in_array('hostel', $vkeys) ? array_shift($hostel_option_matches) : array()
  );

  $product_fees = array();
  $product_hostel_fees = array();
  foreach($matchs['fees'] as $key => $value){
    $product_fees[$key] = $form_state['values'][$value];
  }
  foreach($matchs['fees_options'] as $key => $value) {
    $fees_options['options'] = $form_state['values'][$value];
  }
  foreach($matchs['hostel'] as $key => $value){
    $product_hostel_fees[$key] = $form_state['values'][$value];
  }
  foreach($matchs['hostel_options'] as $key => $value) {
    $hostel_options['options'] = $form_state['values'][$value];
  }
  $cart_items = array(
    'product_item_fees' => array(
      'item' => $product_fees,
      'options' => $fees_options['options']
    ),
    'hostel_item_fees' => array(
      'item' => $product_hostel_fees,
      'options' => in_array('hostel', $vkeys)? $hostel_options['options'] : array()
    )
  );
  // remove all traces of hostel if it's not available
  if(!in_array('hostel', $vkeys)) {
    unset($cart_items['hostel_item_fees']);
  }

  $transaction_token = uniqid();

  uc_cart_empty($student_id);

  $added = FALSE;
  foreach($cart_items as $product_item){
    $cart_item = $product_item;

    foreach($product_item['item'] as $key => $fees_values) {
      $product[$key] = $fees_values;
      $cartId = uc_cart_get_id();
      $nid = $product[$key]['product_nid'];

      if($cart_item['options']['type'] == EDUERP_FEES_NORMAL) {
        if(array_key_exists('attribute_id', $product[$key])){
          $product_attribute = array('attributes' => array($product[$key]['attribute_id'] => $product[$key]['option_id']), 'attribute_id' => $product[$key]['attribute_id'], 'option_id' => $product[$key]['option_id']);
          $options = $cart_item['options'] + $product_attribute;
        }
        else {
          $options = $cart_item['options'];
        }

        // get_fee_items reports 2 states of is_scholarship_applicable
        // @see staff_school_fees_create_modify_fee_item_form()
        // 1: Yes - Scholarship is applicable
        // 2: No - Scholarship is not applicable
        if (!empty($product[$key]['is_scholarship_applicable']) && $product[$key]['is_scholarship_applicable'] == '1' && is_scholarship_authorisation_existing($student_id, variable_get('eduerp_current_session', ''))) {
          $options['has_scholarship'] = '1'; // Yes
        }
        else {
          $options['has_scholarship'] = '2';
        }
      }

      if($cart_item['options']['type'] == EDUERP_FEES_HOSTEL) {
        $options = $cart_item['options'];
      }

      $options['transaction_token'] = $transaction_token;
      $options['original_amount'] = $product[$key]['amount'];

      if ($cart_item['options']['type'] == EDUERP_FEES_HOSTEL) {
        $options['scholarship_type'] = 'None';
        $options['sponsor'] = 'None';
      }
      else {
        $options['scholarship_type'] = $product[$key]['scholarship_type'];
        $options['sponsor'] = $product[$key]['sponsor'];
      }

      $profile_items = uc_eduerp_fees_get_profile_items($cartId);
      foreach($profile_items as $k => $v) {
        $options[$k] = $v;
      }

    if(!empty($product)){
      uc_cart_add_item($product[$key]['product_nid'], 1, $options, $cartId, $msg = TRUE, $check_redirect = TRUE, $rebuild = TRUE);
      $added = TRUE;
      $fees = array(
        'title' => '',
        'type' => $options['type'],
        'description' => $product[$key]['item_description'],
        'nid' => $product[$key]['product_nid'],
        'uid' => $cartId,
        'extras' => serialize($product[$key]['extras']),
        'options' => serialize($options)
      );
    }else {
      drupal_set_message(t('Sorry, you are not eligible to pay fees. Please contact bursary'), 'error');
      watchdog('fees', t('Fees insertion into cart failed on @uid', array('@uid' => $cartId)));
    }
    }
  }
  if($added){
    unset($_SESSION['cart_order']);
    drupal_goto('cart/checkout');
  }
}


/**
 * Implementation of hook_eduerp_fees() to reorganise Fees array
 *
 * <p>Should really be a called as uc_eduerp_fees_eduerp_fees(), no need for call as hook: "module_invoke('uc_eduerp_fees', 'eduerp_fees')".</p>
 * <p>In fact whole array should be flattened and simplified when it is first generated.</p>
 * @uses student_load_student_profile()
 * @param array $fees
 * @return array
 */
function uc_eduerp_fees_eduerp_fees($fees = array()) {
  global $user;

  $type = '';
  $uid = user_load($user->uid);

  static $fees_item;
  $fees_item = get_fee_items($uid->uid);
  if(!empty($fees_item)){
    // Fees
    $fees_item['item'] = $fees_item['fee_item_details'];
    foreach($fees_item['item'] as $key => $value) {
      $description[$key] = $value['item_description'];
      $fees_item['item'][$key]['extras'] = array();
    }

    $profile = student_load_student_profile($uid->uid);
    $fullnames = '';
    if (!empty($profile->profile_first_name) && !empty($profile->profile_last_name)) {
      $middle = '';
      if (!empty($profile->profile_middle_name)) $middle = ' ' . $profile->profile_middle_name;
      $fullnames = "$profile->profile_last_name, $profile->profile_first_name{$middle}";
    }

    $fees_item['options'] = array(
      'type' => EDUERP_FEES_NORMAL,
      'nid' => $fees_item['studentFeeSetupNID'],
      'nationality' =>  $fees_item['nationality_name'],
      'programme' => $fees_item['fee_structure_name'], // Student course
      'level_name' => $fees_item['level_name'],
      'scholarship' => $fees_item['is_student_on_scholarship'], // True or False
      'allow_instalment' => $fees_item['instalment_payment_authorised'], // True or False
      'session' => $fees_item['session_name'],
      'late_registration' => $fees_item['late_reg_info'],
      'jambno' => $profile->profile_matno,
      'fullnames' => $fullnames,
      'institution' => 1
    );

    $fees_item['options']['late_registration']['last_registration_date'] = intval(strtotime($fees_item['options']['late_registration']['last_registration_date']));

    // hostel
    $fees_item['hostel'] = $fees_item['hostel_info'];
    $fees_item['options']['hostel'] = array(
      'nid' => $fees_item['hostel']['product_nid'],
      'type' => EDUERP_FEES_HOSTEL,
      'session' => $fees_item['session_name'],
      'expiry_date' => intval(strtotime($fees_item['hostel']['expiry_date'])),
      'jambno' => $profile->profile_matno,
      'fullnames' => $fullnames,
      'institution' => 1
    );
  } else {
    $fees_item = array();
  }

  $fees['fees'] = array(
    'item' => $fees_item['item'],
    'description' => $description,
    'options' => $fees_item['options'],
    'type' => EDUERP_FEES_NORMAL,
    'title' => t('Fees'), // Human-readable name
  );
  $fees['hostel'] = array(
    'item' => $fees_item['hostel'],
    'description' => $fees_item['hostel']['hostel_description'],
    'options' => $fees_item['options']['hostel'],
    'type' => EDUERP_FEES_HOSTEL,
    'title' => t('Hostel'),
    'extras' => array()
  );
  return $fees;
}

/**
 * Hook to define fees_structure, Don't think this is used, remove?
 *
 * @param $fees
 * @deprecated
 */
function uc_eduerp_fees_eduerp_fees_hook($fees) {
  foreach (module_implements('eduerp_fees') as $module) {
    $function = $module . '_eduerp_fees';
    $result = $function($fees);
    if (isset($result) && is_array($result)) {
      $return = array_merge($return, $result);
    }
    else if (isset($result)) {
      $return[] = $result;
    }
  }
  return $return;
}


/**
 * Not used, remove?
 *
 * @deprecated
 */
function uc_eduerp_fees_invoice_regenerate($order_id) {
  return _uc_eduerp_fees_invoice_rebuild($order_id);
}


/**
 * Not used, remove?
 *
 * @deprecated
 */
function _uc_eduerp_fees_invoice_load($order_id) {
  $view = views_get_view_result('pdf_invoice', 'pdf_1', $order_id);
  $view[0]->uc_orders_order_status = 'canceled';
}


/**
 * Not used, remove?
 *
 * @deprecated
 */
function _uc_eduerp_fees_invoice_rebuild($order_id) {
  return _uc_eduerp_fees_invoice_load($order_id);
}


/**
 * Implements hook_form_ID_alter, not used, remove?
 *
 * <p>Bug: this form alter is getting called before the check
 * for is_reservation_existing. The implication of this is that
 * the hostel form gets removed before a check for whether hostel
 * exists or not.</p>
 * @deprecated
 */
function uc_eduerp_fees_form_uc_eduerp_fees_pay_fees_alter(&$form, $form_state) {
  // Remove hostel if no reservation exists
  if(!is_reservation_existing($form['uid']['#value'])) {
    // unsets from screen, doesn't get removed from from array
    //unset($form['eduerp_fees']['hostel']);
  }
}


/**
 * Implementation of hook_views_api(), register view API information so include files can be loaded
 */
function uc_eduerp_fees_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'uc_eduerp_fees') . '/includes',
  );
}


/**
 * Get Student Profile items related to Fees
 *
 * @param int $uid
 * @return array
 */
function uc_eduerp_fees_get_profile_items($uid) {
  $student_profile = content_profile_load('student_profile', $uid);
  $program = $student_profile->field_profile_first_choice;
  $program_nid = $program[0]['nid'];

  $program_obj = db_fetch_object(db_query("SELECT field_programme_name_value,
    field_department_id_nid FROM {content_type_program} p
    WHERE p.nid = %d", $program_nid));

  if($program_obj) {
    $dept_nid = $program_obj->field_department_id_nid;
    $dept_result = db_result(db_query("SELECT field_college_id_nid
      FROM {content_type_department} d
      WHERE d.nid = %d", $dept_nid));

    if($dept_result) {
      $college_nid = $dept_result;
      $college = db_result(db_query("SELECT field_college_name_value
        FROM {content_type_college} c
        WHERE c.nid = %d", $college_nid));
    }
  }

  $profile_items = array(
    'course' => $program_obj->field_programme_name_value,
    'college' => $college
  );

  return $profile_items;
}