<?php

function portveritas_menu() {
/*
  $items['portveritas/portstudents'] = array(
    'title'=>'Port Students',
    'page callback' => 'drupal_get_form',
    'page arguments'=>array('list_student_for_port_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );
*/

$items['portveritas/portstudents'] = array(
    'title'=>'Port Students',
    'page callback' => 'portstudents',
    'access arguments' => array('staff register course'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}


function portstudents() {
  ob_start();

  echo 'XXXXXXXXXXXXXXXXXXXXXX<br />';

  echo drupal_get_form('list_student_for_port_form');

  return ob_get_clean();
}


function list_student_for_port_form(&$obj) {
  port_student(800);
}


function port_student($student_id) {

  $form['mark'] = array(
    '#value' => '<b>XXXXXXXXXXXXXXXXXXXXXXXX</b>'
  );
/*

  $qry = "select * from {admitted_student} where student_id=%d";
  $res = db_query($qry, $student_id);
  $admitted_student = db_fetch_object($res);


  $q = "SELECT LENGTH(exam_center_name) AS institution, LENGTH(exam_body_name) AS qualification, exam_student_id, LENGTH(grade_name), LENGTH(subject_name)
    FROM admitted_ext_exam_record aeer
    LEFT JOIN
  ext_exam_detail eed, olevel_grades olg, ext_exam_subject ees, ext_exam_body eeb
  WHERE
    aeer.ext_exam_rec_id=eed.ext_exam_record_id AND
    eed.grade_id=olg.grade_id AND
    eed.subject_id=eed.subject_id AND
    aeer.exam_body=eeb.exam_body_id";

  $query3 = " SELECT *
    FROM admitted_ext_exam_record er
    LEFT JOIN admitted_ext_exam_detail ed ON ed.ext_exam_record_id = er.ext_exam_rec_id
    where er.exam_student_id = '". $admitted_student->student_id ."' order by er . ext_exam_rec_id " ;
  $r = db_query($query3);
  while ($f = db_fetch_object($r)) {
    $prev_subjects = $data[$f->ext_exam_rec_id]['subjects'] ;
    $data[$f->ext_exam_rec_id] = array(
      'exam_body ' => $f->exam_body,
      'exam_date' => $f->exam_date,
      'exam_center_name' => $f->exam_center_name,
      'exam_number' => $f->exam_number,
      'exam_body' => $f->exam_body,
    );
    $data[$f->ext_exam_rec_id]['subjects'] = $prev_subjects ;
    $data[$f->ext_exam_rec_id]['subjects'][] = array('subject' => $f->subject_id, 'grade' => $f->grade_id);
    if (!in_array($f->ext_exam_rec_id, $data_key)) {
      $data_key[] = $f->ext_exam_rec_id;
    }
  }

  $qry4 = "SELECT a.programme_id, a . department_id, a . programme_name, b . department_name, c . college_abbreviation, c . college_name FROM `programme` AS a LEFT OUTER JOIN department AS b ON a . department_id = b . department_id LEFT OUTER JOIN college AS c ON b . college_id = c . college_id WHERE a . programme_id='". $admitted_student->first_choice ."'";
  $res4 = db_query($qry4);
  $progdeptcol = db_fetch_object($res4);

  $qry5 = "select a . session_id, b . sess_name from `admitted_student` as a join session as b on a . session_id=b . session_id where a . student_id='". $admitted_student->student_id ."'";
  $res5 = db_query($qry5);
  $sessionx = db_fetch_object($res5);

  $qry6 = "select * from `admitted_next_of_kin` where student_id='". $admitted_student->student_id ."'";
  $res6 = db_query($qry6);
  $admitted_next_of_kin = db_fetch_object($res6);

  $qry7 = "select * from `admitted_sponsor` where student_id='". $admitted_student->student_id ."'";
  $res7 = db_query($qry7);
  $admitted_sponsor = db_fetch_object($res7);

  $form['extra'] = array(
    '#type' => 'fieldset',
    '#title' => 'Admission Information',
    '#collapsed' => TRUE,
    '#collapsible' => TRUE);
  $form['extra']['college0'] = array(
    '#type' => 'item',
    '#title' => 'College',
    '#prefix' => '<table><tr><td>',
    '#suffix' => '</td>');
  $form['extra']['college1'] = array(
    '#type' => 'item',
    '#value' => $progdeptcol->college_abbreviation,
    '#size' => 20,
    '#prefix' => '<td>',
    '#suffix' => '</td>');
  $form['extra']['dept0'] = array(
    '#type' => 'item',
    '#title' => 'Department',
    '#prefix' => '<td>',
    '#suffix' => '</td>');
  $form['extra']['dept1'] = array(
    '#type' => 'item',
    '#value' => $progdeptcol->department_name,
    '#size' => 20,
    '#prefix' => '<td>',
    '#suffix' => '</td>');
  //$form['extra']['space13']=array('#type'=>'item','#prefix'=>'<td>&nbsp;','#suffix'=>'</td>');
  $form['extra']['programme0'] = array(
    '#type' => 'item',
    '#title' => 'Programme',
    '#prefix' => '<td>',
    '#suffix' => '</td>');
  $form['extra']['programme1'] = array(
    '#type' => 'item',
    '#value' => $progdeptcol->programme_name,
    '#size' => 20,
    '#prefix' => '<td>',
    '#suffix' => '</td></tr>');
  $form['extra']['study_mode0'] = array(
    '#type' => 'item',
    '#title' => 'Mode of Study',
    '#prefix' => '<tr><td>',
    '#suffix' => '</td>');
  $form['extra']['study_mode1'] = array(
    '#type' => 'item',
    '#value' => $admitted_student->mode_of_study,
    '#size' => 20,
    '#prefix' => '<td>',
    '#suffix' => '</td>');
  $form['extra']['space14'] = array(
    '#type' => 'item',
    '#prefix' => '<td>&nbsp;',
    '#suffix' => '</td>');
  $form['extra']['entry_mode0'] = array(
    '#type' => 'item',
    '#title' => 'Mode of Entry',
    '#prefix' => '<td>',
    '#suffix' => '</td>');
  $form['extra']['entry_mode1'] = array(
    '#type' => 'item',
    '#size' => 20,
    '#value' => $admitted_student->mode_of_entry,
    '#prefix' => '<td>',
    '#suffix' => '</td>');
  $form['extra']['sess0'] = array(
    '#type' => 'item',
    '#title' => 'SESSION',
    '#prefix' => '<td>',
    '#suffix' => '</td>');
  $form['extra']['sess1'] = array(
    '#type' => 'item',
    '#value' => $sessionx->sess_name,
    '#prefix' => '<td>',
    '#suffix' => '</td></tr></table>',
    '#size' => 15);
  $form['personal'] = array(
    '#type' => 'fieldset',
    '#title' => 'Personal Information',
    '#collapsed' => TRUE,
    '#collapsible' => TRUE);

  $form['personal']['img_lbl0'] = array(
    '#type' => 'item',
    '#title' => 'Student Image',
    '#prefix' => '<table><tr><td>',
    '#suffix' => '</td>');
  $form['personal']['img_lbl1'] = array(
    '#value' => '<img src="'. 'x' .'" />',
    '#prefix' => '<td>',
    '#suffix' => '</td>');
  $form['personal']['space11'] = array(
    '#type' => 'item',
    '#prefix' => '<td>&nbsp;',
    '#suffix' => '</td>');
  $form['personal']['img_sig0'] = array(
    '#type' => 'item',
    '#title' => 'Student Signature',
    '#prefix' => '<td>',
    '#suffix' => '</td>');
  $form['personal']['img_sig1'] = array(
    '#value' => '<img src="'. 'x' .'" />',
    '#prefix' => '<td>',
    '#suffix' => '</td></tr>');
  $form['personal']['matno0'] = array(
    '#type' => 'item',
    '#title' => 'Matriculation No.',
    '#prefix' => '<tr><td>',
    '#suffix' => '</td>');
  $form['personal']['matno1'] = array(
    '#type' => 'item',
    '#size' => 20,
    '#value' => $admitted_student->matriculation_no,
    '#prefix' => '<td>',
    '#suffix' => '</td>');
  $form['personal']['space0'] = array(
    '#type' => 'item',
    '#prefix' => '<td>&nbsp;',
    '#suffix' => '</td>');
  $form['personal']['jambno0'] = array(
    '#type' => 'item',
    '#title' => 'JAMB No.',
    '#prefix' => '<td>',
    '#suffix' => '</td>');
  $form['personal']['jambno1'] = array(
    '#type' => 'item',
    '#size' => 20,
    '#value' => $admitted_student->jambno,
    '#prefix' => '<td>',
    '#suffix' => '</td></tr>');
  $form['personal']['fname0'] = array(
    '#type' => 'item',
    '#title' => 'First Name',
    '#prefix' => '<tr><td>',
    '#suffix' => '</td>');
  $form['personal']['fname1'] = array(
    '#type' => 'item',
    '#size' => 20,
    '#value' => $admitted_student->first_name,
    '#prefix' => '<td>',
    '#suffix' => '</td>');
  $form['personal']['space1'] = array(
    '#type' => 'item',
    '#prefix' => '<td>&nbsp;',
    '#suffix' => '</td>');
  $form['personal']['mname0'] = array(
    '#type' => 'item',
    '#title' => 'Middle Name',
    '#prefix' => '<td>',
    '#suffix' => '</td>');
  $form['personal']['mname1'] = array(
    '#type' => 'item',
    '#size' => 20,
    '#value' => $admitted_student->middle_name,
    '#prefix' => '<td>',
    '#suffix' => '</td>');
  $form['personal']['space2'] = array(
    '#type' => 'item',
    '#prefix' => '<td>&nbsp;',
    '#suffix' => '</td>');
  $form['personal']['lname0'] = array(
    '#type' => 'item',
    '#title' => 'Last Name',
    '#prefix' => '<td>',
    '#suffix' => '</td>');
  $form['personal']['lname1'] = array(
    '#type' => 'item',
    '#size' => 20,
    '#value' => $admitted_student->last_name,
    '#prefix' => '<td>',
    '#suffix' => '</td></tr>');
  $form['personal']['gender0'] = array(
    '#type' => 'item',
    '#title' => 'Gender',
    '#prefix' => '<tr><td>',
    '#suffix' => '</td>');
  $form['personal']['gender1'] = array(
    '#type' => 'item',
    '#size' => 20,
    '#value' => $admitted_student->gender,
    '#prefix' => '<td>',
    '#suffix' => '</td>');
  $form['personal']['space3'] = array(
    '#type' => 'item',
    '#prefix' => '<td>&nbsp;',
    '#suffix' => '</td>');
  $form['personal']['origin0'] = array(
    '#type' => 'item',
    '#title' => 'State Of Origin',
    '#prefix' => '<td>',
    '#suffix' => '</td>');
  $form['personal']['origin1'] = array(
    '#type' => 'select',
    '#options' => veritas_statesXXX(),
    '#default_value' => $admitted_student->state_origin,
    '#prefix' => '<td>',
    '#suffix' => '</td></tr>',
    '#attributes' => array('disabled' => 'disabled'));
  $form['personal']['lga0'] = array(
    '#type' => 'item',
    '#title' => 'LGA Of Origin',
    '#prefix' => '<tr><td>',
    '#suffix' => '</td>');
  $form['personal']['lga1'] = array(
    '#type' => 'select',
    '#options' => veritas_lgaXXX(),
    '#default_value' => $admitted_student->lkup_lga_origin,
    '#prefix' => '<td>',
    '#suffix' => '</td>',
    '#attributes' => array('disabled' => 'disabled'));
  $form['personal']['space4'] = array(
    '#type' => 'item',
    '#prefix' => '<td>&nbsp;',
    '#suffix' => '</td>');
  $form['personal']['mstatus0'] = array(
    '#type' => 'item',
    '#title' => 'Marital Status',
    '#prefix' => '<td>',
    '#suffix' => '</td>');
  $form['personal']['mstatus1'] = array(
    '#type' => 'item',
    '#value' => $admitted_student->marital_status,
    '#size' => 20,
    '#prefix' => '<td>',
    '#suffix' => '</td></tr>');
  $form['personal']['address0'] = array(
    '#type' => 'item',
    '#title' => 'Permanent Address',
    '#prefix' => '<tr><td>',
    '#suffix' => '</td>');
  $form['personal']['address1'] = array(
    '#type' => 'item',
    '#size' => 20,
    '#value' => $admitted_student->permanent_address1,
    '#prefix' => '<td>',
    '#suffix' => '</td>');
  $form['personal']['space5'] = array(
    '#type' => 'item',
    '#prefix' => '<td>&nbsp;',
    '#suffix' => '</td>');
  $form['personal']['city0'] = array(
    '#type' => 'item',
    '#title' => 'City',
    '#prefix' => '<td>',
    '#suffix' => '</td>');
  $form['personal']['city1'] = array(
    '#type' => 'item',
    '#value' => $admitted_student->permanent_address_city,
    '#size' => 20,
    '#prefix' => '<td>',
    '#suffix' => '</td></tr>');
  $form['personal']['state0'] = array(
    '#type' => 'item',
    '#title' => 'State',
    '#prefix' => '<tr><td>',
    '#suffix' => '</td>');
  $form['personal']['state1'] = array(
    '#type' => 'select',
    '#options' => veritas_statesXXX(),
    '#default_value' => $admitted_student->permanent_address_state,
    '#prefix' => '<td>',
    '#suffix' => '</td>',
    '#attributes' => array('disabled' => 'disabled'));
  $form['personal']['space6'] = array(
    '#type' => 'item',
    '#prefix' => '<td>&nbsp;',
    '#suffix' => '</td>');
  $form['personal']['mobile0'] = array(
    '#type' => 'item',
    '#title' => 'Mobile No.',
    '#prefix' => '<td>',
    '#suffix' => '</td>');
  $form['personal']['mobile1'] = array(
    '#type' => 'item',
    '#value' => $admitted_student->mobile_number,
    '#size' => 20,
    '#prefix' => '<td>',
    '#suffix' => '</td></tr>');
  $form['personal']['email0'] = array(
    '#type' => 'item',
    '#title' => 'E-mail address',
    '#prefix' => '<tr><td>',
    '#suffix' => '</td>');
  $form['personal']['email1'] = array(
    '#type' => 'item',
    '#value' => $admitted_student->email_address,
    '#size' => 20,
    '#prefix' => '<td>',
    '#suffix' => '</td>');
  $form['personal']['space15'] = array(
    '#type' => 'item',
    '#prefix' => '<td>&nbsp;',
    '#suffix' => '</td>');
  $form['personal']['health0'] = array(
    '#type' => 'item',
    '#title' => 'Health Status',
    '#prefix' => '<td>',
    '#suffix' => '</td>');
  $form['personal']['health1'] = array(
    '#type' => 'item',
    '#value' => $admitted_student->physical_health_status,
    '#size' => 20,
    '#prefix' => '<td>',
    '#suffix' => '</td></tr></table>');
  $form['nextofkin'] = array(
    '#type' => 'fieldset',
    '#title' => 'Sponsor/Next of Kin Information',
    '#collapsed' => TRUE,
    '#collapsible' => TRUE);
  $form['nextofkin']['nofkin0'] = array(
    '#type' => 'item',
    '#title' => 'Next of Kin Name',
    '#prefix' => '<table><tr><td>',
    '#suffix' => '</td>');
  $form['nextofkin']['nofkin1'] = array(
    '#type' => 'item',
    '#value' => $admitted_next_of_kin->name,
    '#size' => 20,
    '#prefix' => '<td>',
    '#suffix' => '</td>');
  $form['nextofkin']['relation0'] = array(
    '#type' => 'item',
    '#title' => 'Relationship',
    '#prefix' => '<td>',
    '#suffix' => '</td>');
  $form['nextofkin']['relation1'] = array(
    '#type' => 'item',
    '#value' => $admitted_next_of_kin->relationship,
    '#prefix' => '<td>',
    '#suffix' => '</td>');
  $form['nextofkin']['mobile0'] = array(
    '#type' => 'item',
    '#title' => 'Mobile',
    '#prefix' => '<td>',
    '#suffix' => '</td>');
  $form['nextofkin']['mobile1'] = array(
    '#type' => 'item',
    '#value' => $admitted_next_of_kin->mobile,
    '#prefix' => '<td>',
    '#suffix' => '</td></tr>');
  $form['nextofkin']['sponsor0'] = array(
    '#type' => 'item',
    '#title' => 'Sponsor',
    '#prefix' => '<tr><td>',
    '#suffix' => '</td>');
  $form['nextofkin']['sponsor1'] = array(
    '#type' => 'item',
    '#size' => 20,
    '#value' => $admitted_student->sponsor_name,
    '#prefix' => '<td>',
    '#suffix' => '</td>');
  if ($admitted_sponsor->mobile != $admitted_next_of_kin->mobile) {
    $form['nextofkin']['smobile0'] = array(
      '#type' => 'item',
      '#title' => 'Mobile',
      '#prefix' => '<td>',
      '#suffix' => '</td>');
    $form['nextofkin']['smobile1'] = array(
      '#type' => 'item',
      '#size' => 20,
      '#value' => $admitted_sponsor->mobile,
      '#prefix' => '<td>',
      '#suffix' => '</td></tr></table>');
  }
  else {
    $form['nextofkin']['smobile0'] = array(
      '#type' => 'item',
      '#title' => 'Mobile',
      '#prefix' => '<td>',
      '#suffix' => '</td></tr></table>');
  }
  $form['fs'] = array(
    '#type' => 'fieldset',
    '#title' => 'O-Level Results 1st  Sitting',
    '#collapsed' => TRUE,
    '#collapsible' => TRUE);
  $form['fs']['qualification0'] = array(
    '#type' => 'item',
    '#title' => 'QUALIFICATION',
    '#prefix' => '<table><tr><td>',
    '#suffix' => '</td>');
  $form['fs']['qualification1'] = array(
    '#type' => 'item',
    '#value' => $admitted_student->h_qualification1,
    '#prefix' => '<td>',
    '#suffix' => '</td>');
  $form['fs']['space22'] = array(
    '#type' => 'item',
    '#prefix' => '<td>&nbsp;',
    '#suffix' => '</td>');
  $form['fs']['institution0'] = array(
    '#type' => 'item',
    '#title' => 'INSTITUTION',
    '#prefix' => '<td>',
    '#suffix' => '</td>');
  $form['fs']['institution1'] = array(
    '#type' => 'item',
    '#value' => $admitted_student->h_institution1,
    '#prefix' => '<td>',
    '#suffix' => '</td></tr>');
  $form['fs']['ebd0'] = array(
    '#type' => 'item',
    '#title' => 'EXAM BODY',
    '#prefix' => '<tr><td>',
    '#suffix' => '</td>');
  $form['fs']['ebd1'] = array(
    '#type' => 'select',
    '#options' => _student_bodXXX(),
    '#default_value' => $data[$data_key[0]]['exam_body'],
    '#prefix' => '<td>',
    '#suffix' => '</td>',
    '#attributes' => array('disabled' => 'disabled'));
  $form['fs']['space8'] = array(
    '#type' => 'item',
    '#prefix' => '<td>&nbsp;',
    '#suffix' => '</td>');
  $form['fs']['edate0'] = array(
    '#type' => 'item',
    '#title' => 'EXAM DATE',
    '#prefix' => '<td>',
    '#suffix' => '</td>');
  //$form[fs]['edate1'] = array('#type'=>'date','#default_value'=>$data[$data_key[0]]['exam_date'],'#prefix'=>'<td>','#suffix'=>'</td></tr>','#attributes'=>array('disabled' => 'disabled'));
  $form['fs']['edate1'] = array(
    '#type' => 'date',
    '#default_value' => array(
      'day' => (int)substr($data[$data_key[0]]['exam_date'], -2),
      'month' => (int)substr($data[$data_key[0]]['exam_date'], 5, 2),
      'year' => substr($data[$data_key[0]]['exam_date'], 0, 4)),
    '#prefix' => '<td>',
    '#suffix' => '</td></tr>',
    '#attributes' => array('disabled' => 'disabled'));
  $form['fs']['ec0'] = array(
    '#type' => 'item',
    '#title' => 'EXAM CENTER',
    '#prefix' => '<tr><td>',
    '#suffix' => '</td>');
  $form['fs']['ec1'] = array(
    '#type' => 'item',
    '#size' => '20',
    '#value' => $data[$data_key[0]]['exam_center_name'],
    '#prefix' => '<td>',
    '#suffix' => '</td>');
  $form['fs']['space9'] = array(
    '#type' => 'item',
    '#prefix' => '<td>&nbsp;',
    '#suffix' => '</td>');
  $form['fs']['eno0'] = array(
    '#type' => 'item',
    '#title' => 'EXAM NO',
    '#prefix' => '<td>',
    '#suffix' => '</td>');
  $form['fs']['eno1'] = array(
    '#type' => 'item',
    '#size' => '20',
    '#value' => $data[$data_key[0]]['exam_number'],
    '#prefix' => '<td>',
    '#suffix' => '</td></tr></table>');
  $form['fs']['ms1'] = array(
    '#type' => 'item',
    '#value' => 'SUBJECTS',
    '#prefix' => '<table><tr><td></td><th>',
    '#suffix' => '</th>');
  $form['fs']['ms2'] = array(
    '#type' => 'item',
    '#value' => 'GRADE',
    '#prefix' => '<td>',
    '#suffix' => '</td></tr>',
    '#attributes' => array('disabled' => 'disabled'));
  $temp=0;
  for ($i=1;$i<=9;$i++) {
    $temp = $i-1;
    $form['fs']["m1$i"] = array(
      '#value' => '<tr><td>'. $i,
      '#suffix' => '</td>');
    $form['fs']["s1$i"] = array(
      '#type' => 'select',
      '#options' => _student_subXXX(),
      '#prefix' => '<td>',
      '#suffix' => '</td>',
      '#default_value' => $data[$data_key[0]]['subjects'][$temp]['subject'],
      '#attributes' => array('disabled' => 'disabled'));
    if ($i == 9)
      $tend="</table>";
    $form['fs']["g1$i"] = array(
      '#type' => 'select',
      '#options' => _student_grXXX(),
      '#prefix' => '<td>',
      '#suffix' => '</td></tr>'. $tend,
      '#default_value' => $data[$data_key[0]]['subjects'][$temp]['grade'],
      '#attributes' => array('disabled' => 'disabled'));
    $temp = 0;
  }
  unset($data[$data_key[0]]);
//$form[fs]["m12"]=array('#value'=>'</table>');
//ext_exam_rec_id  exam_date  exam_center_name  exam_number  exam_body  exam_student_id  ext_exam_record_id  subject_id  grade_id
  $form['fs2'] = array(
    '#id' => 'setting_sec',
    '#type' => 'fieldset',
    '#title' => 'O-Level Results 2nd Sitting',
    '#collapsed' => TRUE,
    '#collapsible' => TRUE);
  $form['fs2']['qualification10'] = array(
    '#type' => 'item',
    '#title' => 'QUALIFICATION',
    '#prefix' => '<table><tr><td>',
    '#suffix' => '</td>');
  $form['fs2']['qualification11'] = array(
    '#type' => 'item',
    '#value' => $admitted_student->h_qualification2,
    '#prefix' => '<td>',
    '#suffix' => '</td>');
  $form['fs2']['space25'] = array(
    '#type' => 'item',
    '#prefix' => '<td>&nbsp;',
    '#suffix' => '</td>');
  $form['fs2']['institution10'] = array(
    '#type' => 'item',
    '#title' => 'INSTITUTION',
    '#prefix' => '<td>',
    '#suffix' => '</td>');
  $form['fs2']['institution11'] = array(
    '#type' => 'item',
    '#value' => $admitted_student->h_institution2,
    '#prefix' => '<td>',
    '#suffix' => '</td></tr>');
  $form['fs2']['ebd20'] = array(
    '#type' => 'item',
    '#title' => 'EXAM BODY',
    '#prefix' => '<tr><td>',
    '#suffix' => '</td>');
  $form['fs2']['ebd21'] = array(
    '#type' => 'select',
    '#options' => _student_bodXXX(),
    '#default_value' => $data[$data_key[1]]['exam_body'],
    '#prefix' => '<td>',
    '#suffix' => '</td>',
    '#attributes' => array('disabled' => 'disabled'));
  $form['fs2']['space10'] = array(
    '#type' => 'item',
    '#prefix' => '<td>&nbsp;',
    '#suffix' => '</td>');
  $form['fs2']['edate20'] = array(
    '#type' => 'item',
    '#title' => 'EXAM DATE',
    '#prefix' => '<td>',
    '#suffix' => '</td>');
  //$form[fs2]['edate21'] = array('#type'=>'date','#default_value'=>$data[$data_key[1]]['exam_date'], '#prefix'=>'<td>','#suffix'=>'</td></tr>','#attributes'=>array('disabled' => 'disabled'));
  $form['fs2']['edate21'] = array(
    '#type' => 'date',
    '#default_value' => array(
      'day' => (int)substr($data[$data_key[1]]['exam_date'], -2),
      'month' => (int)substr($data[$data_key[1]]['exam_date'], 5, 2),
      'year' => substr($data[$data_key[1]]['exam_date'], 0, 4)),
    '#prefix' => '<td>',
    '#suffix' => '</td></tr>',
    '#attributes' => array('disabled' => 'disabled'));
  $form['fs2']['ec20'] = array(
    '#type' => 'item',
    '#title' => 'EXAM CENTER',
    '#prefix' => '<tr><td>',
    '#suffix' => '</td>');
  $form['fs2']['ec21'] = array(
    '#type' => 'item',
    '#size' => 20,
    '#value' => $data[$data_key[1]]['exam_center_name'],
    '#prefix' => '<td>',
    '#suffix' => '</td>');
  $form['fs2']['space11'] = array(
    '#type' => 'item',
    '#prefix' => '<td>&nbsp;',
    '#suffix' => '</td>');
  $form['fs2']['eno20'] = array(
    '#type' => 'item',
    '#title' => 'EXAM NO',
    '#prefix' => '<td>',
    '#suffix' => '</td>');
  $form['fs2']['eno21'] = array(
    '#type' => 'item',
    '#size' => '20',
    '#value' => $data[$data_key[1]]['exam_number'],
    '#prefix' => '<td>',
    '#suffix' => '</td></tr></table>');
  $form['fs2']['ms11']=array(
    '#type' => 'item',
    '#value' => 'SUBJECTS',
    '#prefix' => '<table><tr><td></td><th>',
    '#suffix' => '</th>');
  $form['fs2']['ms12'] = array(
    '#type' => 'item',
    '#value' => 'GRADE',
    '#prefix' => '<td>',
    '#suffix' => '</td></tr>');
  $tend='';
  for ($i=1;$i<=9;$i++) {
    $temp = $i-1;
    $form['fs2']["m2$i"] = array(
      '#value' => '<tr><td>'. $i,
      '#suffix' => '</td>');
    $form['fs2']["s2$i"] = array(
      '#type' => 'select',
      '#options' => _student_subXXX(),
      '#prefix' => '<td>',
      '#suffix' => '</td>',
      '#default_value' => $data[$data_key[1]]['subjects'][$temp]['subject'],
      '#attributes' => array('disabled' => 'disabled'));
    if ($i == 9)
      $tend="</table>";
    $form['fs2']["g2$i"] = array(
      '#type' => 'select',
      '#options' => _student_grXXX(),
      '#prefix' => '<td>',
      '#suffix' => '</td></tr>'. $tend,
      '#default_value' => $data[$data_key[1]]['subjects'][$temp]['grade'],
      '#attributes' => array('disabled' => 'disabled'));
    $temp = 0;
  }
*/
  return $form;
}


function veritas_lgaXXX() {
  static $ritles;
  if (!$titles) {
    $titles[0] = '';
    $r = db_query("select * from lga order by lga_name");
    while ($f = db_fetch_object($r))
      $titles[$f->lga_id] = $f->lga_name;
  }
  return $titles;
}


function veritas_statesXXX() {
  static $ritles;
  if (!$titles) {
    $titles[0] = '';
    $r = db_query("select * from state order by state_name");
    while ($f = db_fetch_object($r))
      $titles[$f->state_id] = $f->state_name;
  }
  return $titles;
}

function _student_grXXX() {
  static $titles;
  if (!$titles) {
     $titles[] = 'Select';
     $r = db_query("select * from  {olevel_grades} order by grade_name");
     while ($f = db_fetch_object($r))
       $titles[$f->grade_id] = $f->grade_name;
  }
  return  $titles;
}


function _student_subXXX() {
   static $titles;
   if (!$titles) {
      $titles[] = 'Select';
      $r = db_query("select * from  {ext_exam_subject} order by subject_name");
      while ($f = db_fetch_object($r))
       $titles[$f->subject_id]=$f->subject_name;
   }
   return  $titles;
}


function _student_bodXXX() {

  static $titles;
  if (!$titles) {
    $titles[] = 'Select';
    $r = db_query("select * from {ext_exam_body}  order by exam_body_name");
    while ($f = db_fetch_object($r))
      $titles[$f->exam_body_id] = $f->exam_body_name;
    }
   return  $titles;
}
?>
