<?php
$view = new view;
$view->name = 'course_grades';
$view->description = '';
$view->tag = '';
$view->view_php = '';
$view->base_table = 'node';
$view->is_cacheable = FALSE;
$view->api_version = 2;
$view->disabled = FALSE; /* Edit this to true to make a default view disabled initially */
$handler = $view->new_display('default', 'Defaults', 'default');
$handler->override_option('relationships', array(
  'field_mat_no_uid' => array(
    'label' => 'Student',
    'required' => 0,
    'delta' => -1,
    'id' => 'field_mat_no_uid',
    'table' => 'node_data_field_mat_no',
    'field' => 'field_mat_no_uid',
    'relationship' => 'none',
  ),
  'field_course_instance_nid' => array(
    'label' => 'Course Instance',
    'required' => 1,
    'delta' => -1,
    'id' => 'field_course_instance_nid',
    'table' => 'node_data_field_course_instance',
    'field' => 'field_course_instance_nid',
    'relationship' => 'none',
  ),
  'field_course_id_nid' => array(
    'label' => 'Course',
    'required' => 1,
    'delta' => -1,
    'id' => 'field_course_id_nid',
    'table' => 'node_data_field_course_id',
    'field' => 'field_course_id_nid',
    'relationship' => 'field_course_instance_nid',
  ),
  'content_profile_rel' => array(
    'label' => 'Content Profile',
    'required' => 0,
    'type' => 'profile',
    'id' => 'content_profile_rel',
    'table' => 'users',
    'field' => 'content_profile_rel',
    'relationship' => 'field_mat_no_uid',
  ),
));
$handler->override_option('fields', array(
  'name' => array(
    'label' => 'MAT No.',
    'alter' => array(
      'alter_text' => 0,
      'text' => '',
      'make_link' => 0,
      'path' => '',
      'link_class' => '',
      'alt' => '',
      'prefix' => '',
      'suffix' => '',
      'target' => '',
      'help' => '',
      'trim' => 0,
      'max_length' => '',
      'word_boundary' => 1,
      'ellipsis' => 1,
      'html' => 0,
      'strip_tags' => 0,
    ),
    'empty' => '',
    'hide_empty' => 0,
    'empty_zero' => 0,
    'link_to_user' => 1,
    'overwrite_anonymous' => 0,
    'anonymous_text' => '',
    'exclude' => 0,
    'id' => 'name',
    'table' => 'users',
    'field' => 'name',
    'relationship' => 'field_mat_no_uid',
  ),
  'field_profile_last_name_value' => array(
    'label' => 'Last Name',
    'alter' => array(
      'alter_text' => 0,
      'text' => '',
      'make_link' => 0,
      'path' => '',
      'link_class' => '',
      'alt' => '',
      'prefix' => '',
      'suffix' => '',
      'target' => '',
      'help' => '',
      'trim' => 0,
      'max_length' => '',
      'word_boundary' => 1,
      'ellipsis' => 1,
      'html' => 0,
      'strip_tags' => 0,
    ),
    'empty' => '',
    'hide_empty' => 0,
    'empty_zero' => 0,
    'link_to_node' => 1,
    'label_type' => 'widget',
    'format' => 'default',
    'multiple' => array(
      'group' => TRUE,
      'multiple_number' => '',
      'multiple_from' => '',
      'multiple_reversed' => FALSE,
    ),
    'exclude' => 0,
    'id' => 'field_profile_last_name_value',
    'table' => 'node_data_field_profile_last_name',
    'field' => 'field_profile_last_name_value',
    'relationship' => 'content_profile_rel',
  ),
  'field_profile_first_name_value' => array(
    'label' => 'First Name',
    'alter' => array(
      'alter_text' => 0,
      'text' => '',
      'make_link' => 0,
      'path' => '',
      'link_class' => '',
      'alt' => '',
      'prefix' => '',
      'suffix' => '',
      'target' => '',
      'help' => '',
      'trim' => 0,
      'max_length' => '',
      'word_boundary' => 1,
      'ellipsis' => 1,
      'html' => 0,
      'strip_tags' => 0,
    ),
    'empty' => '',
    'hide_empty' => 0,
    'empty_zero' => 0,
    'link_to_node' => 1,
    'label_type' => 'widget',
    'format' => 'default',
    'multiple' => array(
      'group' => TRUE,
      'multiple_number' => '',
      'multiple_from' => '',
      'multiple_reversed' => FALSE,
    ),
    'exclude' => 0,
    'id' => 'field_profile_first_name_value',
    'table' => 'node_data_field_profile_first_name',
    'field' => 'field_profile_first_name_value',
    'relationship' => 'content_profile_rel',
  ),
  'field_profile_middle_name_value' => array(
    'label' => 'Middle Name',
    'alter' => array(
      'alter_text' => 0,
      'text' => '',
      'make_link' => 0,
      'path' => '',
      'link_class' => '',
      'alt' => '',
      'prefix' => '',
      'suffix' => '',
      'target' => '',
      'help' => '',
      'trim' => 0,
      'max_length' => '',
      'word_boundary' => 1,
      'ellipsis' => 1,
      'html' => 0,
      'strip_tags' => 0,
    ),
    'empty' => '',
    'hide_empty' => 0,
    'empty_zero' => 0,
    'link_to_node' => 0,
    'label_type' => 'widget',
    'format' => 'default',
    'multiple' => array(
      'group' => TRUE,
      'multiple_number' => '',
      'multiple_from' => '',
      'multiple_reversed' => FALSE,
    ),
    'exclude' => 0,
    'id' => 'field_profile_middle_name_value',
    'table' => 'node_data_field_profile_middle_name',
    'field' => 'field_profile_middle_name_value',
    'relationship' => 'content_profile_rel',
  ),
  'field_ca1_value' => array(
    'label' => 'CA1',
    'link_to_node' => 0,
    'label_type' => 'widget',
    'format' => 'clicktoedit',
    'multiple' => array(
      'group' => TRUE,
      'multiple_number' => '',
      'multiple_from' => '',
      'multiple_reversed' => FALSE,
    ),
    'exclude' => 0,
    'id' => 'field_ca1_value',
    'table' => 'node_data_field_ca1',
    'field' => 'field_ca1_value',
    'override' => array(
      'button' => 'Override',
    ),
    'relationship' => 'none',
  ),
  'field_ca2_value' => array(
    'label' => 'CA2',
    'link_to_node' => 0,
    'label_type' => 'widget',
    'format' => 'clicktoedit',
    'multiple' => array(
      'group' => TRUE,
      'multiple_number' => '',
      'multiple_from' => '',
      'multiple_reversed' => FALSE,
    ),
    'exclude' => 0,
    'id' => 'field_ca2_value',
    'table' => 'node_data_field_ca2',
    'field' => 'field_ca2_value',
    'override' => array(
      'button' => 'Override',
    ),
    'relationship' => 'none',
  ),
  'field_ca3_value' => array(
    'label' => 'CA3',
    'link_to_node' => 0,
    'label_type' => 'widget',
    'format' => 'clicktoedit',
    'multiple' => array(
      'group' => TRUE,
      'multiple_number' => '',
      'multiple_from' => '',
      'multiple_reversed' => FALSE,
    ),
    'exclude' => 0,
    'id' => 'field_ca3_value',
    'table' => 'node_data_field_ca3',
    'field' => 'field_ca3_value',
    'relationship' => 'none',
  ),
  'field_ca4_value' => array(
    'label' => 'CA4',
    'link_to_node' => 0,
    'label_type' => 'widget',
    'format' => 'clicktoedit',
    'multiple' => array(
      'group' => TRUE,
      'multiple_number' => '',
      'multiple_from' => '',
      'multiple_reversed' => FALSE,
    ),
    'exclude' => 0,
    'id' => 'field_ca4_value',
    'table' => 'node_data_field_ca4',
    'field' => 'field_ca4_value',
    'relationship' => 'none',
  ),
  'field_exam_score_value' => array(
    'label' => 'Exam Score',
    'link_to_node' => 0,
    'label_type' => 'widget',
    'format' => 'clicktoedit',
    'multiple' => array(
      'group' => TRUE,
      'multiple_number' => '',
      'multiple_from' => '',
      'multiple_reversed' => FALSE,
    ),
    'exclude' => 0,
    'id' => 'field_exam_score_value',
    'table' => 'node_data_field_exam_score',
    'field' => 'field_exam_score_value',
    'relationship' => 'none',
  ),
  'field_total_score_value' => array(
    'label' => 'Total Score',
    'link_to_node' => 0,
    'label_type' => 'widget',
    'format' => 'addnidtohtml',
    'multiple' => array(
      'group' => TRUE,
      'multiple_number' => '',
      'multiple_from' => '',
      'multiple_reversed' => FALSE,
    ),
    'exclude' => 0,
    'id' => 'field_total_score_value',
    'table' => 'node_data_field_total_score',
    'field' => 'field_total_score_value',
    'relationship' => 'none',
  ),
  'field_grade_value' => array(
    'label' => 'Grade',
    'link_to_node' => 0,
    'label_type' => 'widget',
    'format' => 'addnidtohtml',
    'multiple' => array(
      'group' => TRUE,
      'multiple_number' => '',
      'multiple_from' => '',
      'multiple_reversed' => FALSE,
    ),
    'exclude' => 0,
    'id' => 'field_grade_value',
    'table' => 'node_data_field_grade',
    'field' => 'field_grade_value',
    'relationship' => 'none',
  ),
  'field_comment_grades_value' => array(
    'label' => 'Comment',
    'link_to_node' => 0,
    'label_type' => 'widget',
    'format' => 'clicktoedit',
    'multiple' => array(
      'group' => TRUE,
      'multiple_number' => '',
      'multiple_from' => '',
      'multiple_reversed' => FALSE,
    ),
    'exclude' => 0,
    'id' => 'field_comment_grades_value',
    'table' => 'node_data_field_comment_grades',
    'field' => 'field_comment_grades_value',
    'relationship' => 'none',
  ),
));
$handler->override_option('filters', array(
  'type' => array(
    'operator' => 'in',
    'value' => array(
      'student_grades' => 'student_grades',
    ),
    'group' => '0',
    'exposed' => FALSE,
    'expose' => array(
      'operator' => FALSE,
      'label' => '',
    ),
    'id' => 'type',
    'table' => 'node',
    'field' => 'type',
    'relationship' => 'none',
  ),
  'field_code_value_many_to_one' => array(
    'operator' => 'or',
    'value' => array(),
    'group' => '0',
    'exposed' => TRUE,
    'expose' => array(
      'use_operator' => 0,
      'operator' => 'field_code_value_many_to_one_op',
      'identifier' => 'coursecode',
      'label' => 'Course code',
      'optional' => 0,
      'single' => 1,
      'remember' => 1,
      'reduce' => 0,
    ),
    'id' => 'field_code_value_many_to_one',
    'table' => 'node_data_field_code',
    'field' => 'field_code_value_many_to_one',
    'relationship' => 'field_course_id_nid',
    'reduce_duplicates' => 0,
  ),
  'field_sess_name_value_many_to_one' => array(
    'operator' => 'or',
    'value' => array(),
    'group' => '0',
    'exposed' => TRUE,
    'expose' => array(
      'use_operator' => 0,
      'operator' => 'field_sess_name_value_many_to_one_op',
      'identifier' => 'session',
      'label' => 'Session',
      'optional' => 0,
      'single' => 1,
      'remember' => 1,
      'reduce' => 0,
    ),
    'id' => 'field_sess_name_value_many_to_one',
    'table' => 'node_data_field_sess_name',
    'field' => 'field_sess_name_value_many_to_one',
    'relationship' => 'field_course_instance_nid',
    'reduce_duplicates' => 0,
  ),
  'field_semester_name_value_many_to_one' => array(
    'operator' => 'or',
    'value' => array(),
    'group' => '0',
    'exposed' => TRUE,
    'expose' => array(
      'use_operator' => 0,
      'operator' => 'field_semester_name_value_many_to_one_op',
      'identifier' => 'semester',
      'label' => 'Semester',
      'optional' => 0,
      'single' => 1,
      'remember' => 1,
      'reduce' => 0,
    ),
    'id' => 'field_semester_name_value_many_to_one',
    'table' => 'node_data_field_semester_name',
    'field' => 'field_semester_name_value_many_to_one',
    'relationship' => 'field_course_instance_nid',
    'reduce_duplicates' => 0,
  ),
  'field_location_value_many_to_one' => array(
    'operator' => 'or',
    'value' => array(),
    'group' => '0',
    'exposed' => TRUE,
    'expose' => array(
      'use_operator' => 0,
      'operator' => 'field_location_value_many_to_one_op',
      'identifier' => 'location',
      'label' => 'Location',
      'optional' => 1,
      'single' => 1,
      'remember' => 1,
      'reduce' => 0,
    ),
    'id' => 'field_location_value_many_to_one',
    'table' => 'node_data_field_location',
    'field' => 'field_location_value_many_to_one',
    'relationship' => 'field_course_instance_nid',
    'reduce_duplicates' => 0,
  ),
  'field_dropped_value' => array(
    'operator' => '=',
    'value' => array(
      'value' => '0',
      'min' => '',
      'max' => '',
    ),
    'group' => '0',
    'exposed' => FALSE,
    'expose' => array(
      'operator' => FALSE,
      'label' => '',
    ),
    'id' => 'field_dropped_value',
    'table' => 'node_data_field_dropped',
    'field' => 'field_dropped_value',
    'relationship' => 'none',
  ),
));
$handler->override_option('access', array(
  'type' => 'perm',
  'perm' => 'view grading',
));
$handler->override_option('cache', array(
  'type' => 'none',
));
$handler->override_option('footer', '<?php
require_once \'./\' . drupal_get_path(\'module\', \'eduerp\') . \'/grading/course_grades_footer.inc\';
?>');
$handler->override_option('footer_format', '3');
$handler->override_option('footer_empty', 0);
$handler->override_option('items_per_page', 100);
$handler->override_option('use_pager', '1');
$handler->override_option('distinct', 1);
$handler->override_option('style_plugin', 'table');
$handler->override_option('style_options', array(
  'grouping' => '',
  'override' => 1,
  'sticky' => 0,
  'order' => 'asc',
  'columns' => array(
    'name' => 'name',
    'field_profile_last_name_value' => 'field_profile_last_name_value',
    'field_profile_first_name_value' => 'field_profile_first_name_value',
    'field_profile_middle_name_value' => 'field_profile_middle_name_value',
    'field_ca1_value' => 'field_ca1_value',
    'field_ca2_value' => 'field_ca2_value',
    'field_ca3_value' => 'field_ca3_value',
    'field_ca4_value' => 'field_ca4_value',
    'field_exam_score_value' => 'field_exam_score_value',
    'field_total_score_value' => 'field_total_score_value',
    'field_grade_value' => 'field_grade_value',
    'field_comment_grades_value' => 'field_comment_grades_value',
  ),
  'info' => array(
    'name' => array(
      'sortable' => 1,
      'separator' => '',
    ),
    'field_profile_last_name_value' => array(
      'sortable' => 1,
      'separator' => '',
    ),
    'field_profile_first_name_value' => array(
      'sortable' => 1,
      'separator' => '',
    ),
    'field_profile_middle_name_value' => array(
      'sortable' => 0,
      'separator' => '',
    ),
    'field_ca1_value' => array(
      'sortable' => 1,
      'separator' => '',
    ),
    'field_ca2_value' => array(
      'sortable' => 1,
      'separator' => '',
    ),
    'field_ca3_value' => array(
      'sortable' => 1,
      'separator' => '',
    ),
    'field_ca4_value' => array(
      'sortable' => 1,
      'separator' => '',
    ),
    'field_exam_score_value' => array(
      'sortable' => 1,
      'separator' => '',
    ),
    'field_total_score_value' => array(
      'sortable' => 1,
      'separator' => '',
    ),
    'field_grade_value' => array(
      'sortable' => 1,
      'separator' => '',
    ),
    'field_comment_grades_value' => array(
      'sortable' => 0,
      'separator' => '',
    ),
  ),
  'default' => 'field_profile_last_name_value',
));
$handler = $view->new_display('page', 'Page', 'page_1');
$handler->override_option('path', 'course');
$handler->override_option('menu', array(
  'type' => 'none',
  'title' => '',
  'description' => '',
  'weight' => 0,
  'name' => 'navigation',
));
$handler->override_option('tab_options', array(
  'type' => 'none',
  'title' => '',
  'description' => '',
  'weight' => 0,
  'name' => 'navigation',
));
