<?php

function importudus_menu() {

$items['importudus/importstudents'] = array(
    'title'=>'Import Students',
    'page callback' => 'importstudents',
    'access arguments' => array('administer users'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}


function importstudents() {
  ob_start();

//!!!remove matno

$sql = "SELECT * FROM {importsokoto} i WHERE i.uid=0 AND field_profile_matno_value='X821903017' LIMIT 100";
$imports = db_query($sql);
$number_imported = 0;
while ($import = db_fetch_object($imports)) {

  $mat   = $import->field_profile_matno_value;
  $email = $mat . '@udusok.edu.ng';

  $dob          = $import->field_profile_dob_value;
  $last         = $import->field_profile_last_name_value;
  $first        = $import->field_profile_first_name_value;
  $middle       = $import->field_profile_middle_name_value;
  $program_name = $import->field_profile_first_choice;

  if (!empty($import->field_scholarship_sponsor_value)) {
    $profile_sponsor_name = $import->field_scholarship_sponsor_value;
  }
  else {
    $profile_sponsor_name = NULL;
  }

  if (!empty($import->field_profile_state_sponsor_value)) {
    $profile_state_sponsor = $import->field_profile_state_sponsor_value;
  }
  else {
    $profile_state_sponsor = NULL;
  }

  $sql = "SELECT p.nid FROM {content_type_program} p WHERE p.field_programme_name_value='%s'";
  $result = db_query($sql, $programme_name);
  $row = db_fetch_object($result);
  $program_nid = $row->nid;

  $newUser = array(
    'name' => $mat,
    'pass' => $dob,
    'mail' => $email,
    'init' => $email,
    'status' => 1,

    'roles' => array(7 => 'Student'),

    'profile_last_name'   => $last,
    'profile_first_name'  => $first,
    'profile_middle_name' => $middle,

    'profile_dob' => $dob,

    'profile_matno'             => $mat,
    'profile_jambno'            => 'none',
    'university_email'          => $email,
    'profile_reg_session'       => '2010/2011',
    'profile_reg_semester'      => 2,
    'profile_title_name'        => $import->field_profile_title_name_value,
    'profile_gender_value'      => $import->field_profile_gender_value,
    'profile_country_name'      => $import->field_profile_country_name_value,
    'profile_health_status'     => $import->field_profile_health_status_value,
    'profile_yearofentry'       => $import->field_profile_yearofentry_value,
    'profile_mode_of_entry'     => $import->field_profile_mode_of_entry_value,
    'profile_mode_of_study'     => $import->field_profile_mode_of_study_value,
    'profile_level_name'        => $import->field_profile_level_name_value,
    'profile_state_name_origin' => $import->field_profile_state_name_origin_value,
    'profile_sponsor_name'      => $profile_sponsor_name,
    'profile_state_sponsor'     => $profile_state_sponsor,
  );

  user_save(NULL, $newUser);
  $uid = db_last_insert_id('users', 'uid');

  db_query("UPDATE import_sokoto SET uid=%d, imported=1 WHERE field_profile_matno_value='%s'", $uid, $mat);

  // Should do Zimbra automatically
  // Should do profile & student_profile automatically

  $node = new stdClass();
  $node->type    = 'student_program';
  $node->uid     = 1;  // Admin
  $node->status  = 1;  // Published
  $node->promote = 0;
  $node->sticky  = 0;
  $node->comment = 0;

  if (!empty($middle)) $middle = $middle . ' ';
  $name = "$first {$middle}$last";

  $node->title                                      = "$name - $program_name";
  $node->field_student_ref_sp[0]['uid']             = $uid;
  $node->field_program_ref_sp[0]['nid']             = $program_nid;
  $node->field_cgpa_sp[0]['value']                  = '-';
  $node->field_cgpaforstudent_sp[0]['value']        = '-';
  $node->field_gptotal_sp[0]['value']               = '-';
  $node->field_credit_load_completed_sp[0]['value'] = 0;
  node_save($node);
  $student_program = $node->nid;

  $year_1_session = 2010;
  $year_2_session = 2011;
  for ($level = $import->field_profile_level_name_value; $year_1_session >= $import->field_profile_yearofentry_value; $level -= 100) {
    $session = "$year_1_session/$year_2_session";

    foreach (array(1, 2) as $semester) {
      $node = new stdClass();
      $node->type                                    = 'student_gpa';
      $node->uid                                     = 1;  // Admin
      $node->status                                  = 1;  // Published
      $node->promote                                 = 0;
      $node->sticky                                  = 0;
      $node->comment                                 = 0;
      $node->title                                   = "$name - $session - $semester";
      $node->field_student_ref_gpa[0]['uid']         = $uid;
      $node->field_sess_name_gpa[0]['value']         = $session;
      $node->field_semester_name_gpa[0]['value']     = $semester;
      $node->field_program_ref_gpa[0]['nid']         = $program_nid;
      $node->field_student_program_ref_gpa[0]['nid'] = $student_program;
      $node->field_gptotal[0]['value']               = '-';
      $node->field_gpa[0]['value']                   = '-';
      $node->field_gpaforstudent[0]['value']         = '-';
      $node->field_credit_load_registered[0]['value']= 0;
      $node->field_credit_load_completed[0]['value'] = 0;
      $node->field_level_name_gpa[0]['value']        = $level;
      node_save($node);
    }

    $year_1_session--;
    $year_2_session--;
  }
  $number_imported++;
}

echo "Imported $number_imported Students<br />";

return ob_get_clean();
}
?>
